Don't use compacted data when parsing accounts
friendica/friendica pull request #10257
Opened 2021-05-16 16:44 UTC by annando

This is a follow up fix for the defunct URL `https://w3id.org/security/v1`. we now don't use compacted data when fetching account data.

I tested against some accounts from several systems - this seemed to work. But it could happen that some exotic systems send data in a format that we now can't parse anymore. We have to see this in the future.

2021-05-16 17:29 UTC, MrPetovan approved these changes

2021-05-16 17:29 UTC, MrPetovan commented on src/Model/APContact.php
>  			}
```suggestion
			$following = ActivityPub::fetchContent($apcontact['following']);
			if (!empty($following['totalItems'])) {
				$apcontact['following_count'] = $following['totalItems'];
			}
```

2021-05-16 17:29 UTC, MrPetovan commented on src/Model/APContact.php
>  			}
```suggestion
			$followers = ActivityPub::fetchContent($apcontact['followers']);
			if (!empty($followers['totalItems'])) {
				$apcontact['followers_count'] = $followers['totalItems'];
			}
```

2021-05-16 17:29 UTC, MrPetovan commented on src/Model/APContact.php
>  			}
```suggestion
			$outbox = ActivityPub::fetchContent($apcontact['outbox']);
			if (!empty($outbox['totalItems'])) {
				$apcontact['statuses_count'] = $outbox['totalItems'];
			}
```

2021-05-16 17:30 UTC, MrPetovan requested changes
Please remove the duplicated conditions and rename the variables.

2021-05-16 20:08 UTC, MrPetovan approved these changes

2021-05-16 21:11 UTC, annando commented
@MrPetovan I'm still fighting with the issue. Although the messages are accepted again, the signature check doesn't work with all senders.

2021-05-16 23:41 UTC, MrPetovan requested changes

2021-05-16 23:41 UTC, MrPetovan commented on static/w3id-security-v1.json
> +  }
Coding standards: Please add an EOF EOL.
```suggestion
}

```

2021-05-16 23:41 UTC, MrPetovan commented on static/w3id-security-v1.json
> +      "id": "@id",
Code standards: Inconsistent indentation, please choose 2 or 4-spaces indentation for the whole file.

2021-05-17 06:09 UTC, annando commented
I reverted most of my yesterday's panic coding. It is replaced with a loader that fetches the definitions locally if they are known.

2021-05-17 07:58 UTC, MrPetovan approved these changes

2021-05-17 07:58 UTC, merged