API: Search endpoint
friendica/friendica pull request #10261
Opened 2021-05-17 22:23 UTC by annando

The search endpoint is now enabled as well.

2021-05-17 23:18 UTC, MrPetovan requested changes

2021-05-17 23:18 UTC, MrPetovan commented on src/Module/Api/Mastodon/Accounts/Search.php
> +		$resolve = (bool)!isset($_REQUEST['resolve']) ? false : ($_REQUEST['resolve'] == 'true');
```suggestion
		$resolve = ($_REQUEST['resolve'] ?? false) == 'true';
```

2021-05-17 23:18 UTC, MrPetovan commented on src/Module/Api/Mastodon/Accounts/Search.php
> +		$following = (bool)!isset($_REQUEST['following']) ? false : ($_REQUEST['following'] == 'true');
```suggestion
		$following = ($_REQUEST['following'] ?? false) == 'true';
```

2021-05-17 23:18 UTC, MrPetovan commented on src/Module/Api/Mastodon/Search.php
> +		$resolve = (bool)!isset($_REQUEST['resolve']) ? false : ($_REQUEST['resolve'] == 'true');
```suggestion
		$resolve = ($_REQUEST['resolve'] ?? false) == 'true';
```

2021-05-17 23:18 UTC, MrPetovan commented on src/Module/Api/Mastodon/Search.php
> +		$following = (bool)!isset($_REQUEST['following']) ? false : ($_REQUEST['following'] == 'true');
```suggestion
		$following = ($_REQUEST['following'] ?? false) == 'true';
```

2021-05-17 23:18 UTC, MrPetovan commented on src/Module/Api/Mastodon/Search.php
> +		$exclude_unreviewed = (bool)!isset($_REQUEST['exclude_unreviewed']) ? false : ($_REQUEST['exclude_unreviewed'] == 'true');
```suggestion
		$exclude_unreviewed = ($_REQUEST['exclude_unreviewed'] ?? false) == 'true';
```

2021-05-18 07:09 UTC, annando commented
I added a new mechanism to check default values and presence of request parameters. This helps in two way:

1. a centralized check helps in applying changes if we have to adapt to some client behaviour (when for example a client is sending a boolean value as real boolean value)
2. We can easily detect if clients are transmitting undocumented parameters. I already experienced this. And I only found this by random.

I kept assigning the request array to variables. Doing so enables us to easily detect if we already handled that variable. Also we have a place to document the parameters.

I applied the changes only to two selected places since I'm awaiting your approval for that. Then I would convert all places.

2021-05-18 11:33 UTC, MrPetovan approved these changes

2021-05-18 11:36 UTC, merged

2021-05-18 13:24 UTC, annando commented
I had expected some discussions :-) So you like this way?

2021-05-18 15:10 UTC, MrPetovan commented
Huh, I didn't see what you did, I probably missed it in a partial diff, but it looks good to me.