API: Unified request parameter handling
friendica/friendica pull request #10329
Opened 2021-05-28 06:16 UTC by annando

We are now processing (nearly) all requests throufh a unified functionality. Now it doesn't matter anymore if an incoming API request had been done via PUT, PATCH or POST or if it had been done as formdata or JSON.

2021-05-28 16:10 UTC, MrPetovan requested changes

2021-05-28 16:10 UTC, MrPetovan commented on src/Module/Api/Mastodon/Lists.php
> +			'replies_policy' => '', // Enumerable oneOf followed list none.
"followed list none"?

2021-05-28 16:10 UTC, MrPetovan commented on src/Module/BaseApi.php
>  	public static function getRequest(array $defaults) {
Code standards: Please add a new line before method opening braces.
```suggestion
	public static function getRequest(array $defaults)
	{
```

2021-05-29 10:38 UTC, annando commented on src/Module/Api/Mastodon/Lists.php
> +			'replies_policy' => '', // Enumerable oneOf followed list none.
It's a direct copy and paste.

2021-05-29 12:29 UTC, MrPetovan commented on src/Module/Api/Mastodon/Lists.php
> +			'replies_policy' => '', // Enumerable oneOf followed list none.
Without the original formatting it doesn't work as well.
```suggestion
			'replies_policy' => '', // Enumerable. One of: "followed", "list", or "none".
```

2021-05-29 12:30 UTC, MrPetovan requested changes

2021-05-29 12:30 UTC, MrPetovan commented on src/Module/Api/Mastodon/Statuses.php
> +			'visibility'     => '',    // Visibility of the posted status. Enumerable oneOf public, unlisted, private, direct.
```suggestion
			'visibility'     => '',    // Visibility of the posted status. One of: "public", "unlisted", "private" or "direct".
```

2021-05-29 12:30 UTC, MrPetovan commented on src/Module/Api/Mastodon/Lists.php
> +			'replies_policy' => '', // Enumerable oneOf followed list none.
Without the original formatting it doesn't work as well.
```suggestion
			'replies_policy' => '', // One of: "followed", "list", or "none".
```

2021-05-29 14:53 UTC, MrPetovan approved these changes

2021-05-29 14:53 UTC, merged