Adjusted documentation
friendica/friendica pull request #10429
Opened 2021-06-24 18:17 UTC by annando

The Mastodon API documentation is adjusted.

2021-06-24 18:52 UTC, MrPetovan requested changes

2021-06-24 18:52 UTC, MrPetovan commented on doc/FAQ.md
> +- [Halycon](https://www.halcyon.social/)
Typo.
```suggestion
- [Halcyon](https://www.halcyon.social/)
```

2021-06-24 18:52 UTC, MrPetovan commented on doc/FAQ.md
> +#### Desktop
Halcyon and Pinafore are web frontends, not desktop software.

2021-06-24 20:20 UTC, annando commented on doc/FAQ.md
> +- [Halycon](https://www.halcyon.social/)
It's a complicate name :grin:

2021-06-25 00:29 UTC, MrPetovan approved these changes

2021-06-25 00:30 UTC, merged