Issue 10640: Some more inversed settings
friendica/friendica pull request #10647
Opened 2021-08-31 19:27 UTC by annando

See #10640

These are some more settings which now are inversed, so that they now enable and not disable the setting.

2021-08-31 20:00 UTC, MrPetovan requested changes

2021-08-31 20:00 UTC, MrPetovan commented on src/Module/Admin/Site.php
> +		$enable_regfullname     = !empty($_POST['enable_regfullname']);
```suggestion
		$enable_multi_reg       = !empty($_POST['enable_multi_reg']);
		$enable_openid          = !empty($_POST['enable_openid']);
		$enable_regfullname     = !empty($_POST['enable_regfullname']);
```

2021-08-31 20:00 UTC, MrPetovan commented on src/Module/Admin/Site.php
> +			'$enable_regfullname'     => ['enable_regfullname', DI::l10n()->t('Enable Fullname check'), !DI::config()->get('system', 'no_regfullname'), DI::l10n()->t('Enable check to only allow users to regis
```suggestion
			'$enable_multi_reg'       => ['enable_multi_reg', DI::l10n()->t('Enable multiple registrations'), !DI::config()->get('system', 'block_extended_register'), DI::l10n()->t('Enable users to register additional accounts for use as pages.')],
			'$enable_openid'          => ['enable_openid', DI::l10n()->t('Enable OpenID'), !DI::config()->get('system', 'no_openid'), DI::l10n()->t('Enable OpenID support for registration and logins.')],
			'$enable_regfullname'     => ['enable_regfullname', DI::l10n()->t('Enable Fullname check'), !DI::config()->get('system', 'no_regfullname'), DI::l10n()->t('Enable check to only allow users to register with a space between the first name and the last name in their full name.')],
```

2021-08-31 20:01 UTC, MrPetovan approved these changes

2021-08-31 20:02 UTC, MrPetovan commented
Are these the last of the "Disable ..." settings or was it just for the Admin settings?

2021-08-31 20:05 UTC, merged

2021-08-31 20:47 UTC, annando commented
I'm not totally sure with some settings, for example the "unlisted" setting in the user settings. I guess the best would be if someone else could also have a look.

2021-09-01 08:41 UTC, foss- commented
Thanks for working on this. Display Settings > Content/Layout still has:

- Don't shot emoticons: Should be `Show emoticons` (Enabled by default)
- Disable smart threading: Should be `Enable smart threading` (Enabled by default)
- Hide the dislike feature: Should be `Show dislikes` (Enabled by default)

Slightly Off-topic, but what do you think about renaming `Content/Layout` to `Timeline Layout`? I don't think Word1/Word2 as a title for a section is good UX.

<img width="648" alt="display settings   Content:Layout" src="https://user-images.githubusercontent.com/5708172/131639946-1bd0a7d8-5a68-4813-9bdb-dcd9fb70d3ee.png">