Feat/storage refactor
friendica/friendica pull request #10825
Opened 2021-10-04 08:48 UTC by nupplaphil

Splitting the `IWritableStorage`:

- `IWritableStorage` for CRUD operations at the storage backend
- `IStorageConfiguration` to configure the storage backend

@MrPetovan  It wasn't **that** easy because of the dynamic options fetching and saving, so I had to adapt some parts of `Core\StorageManager` and `Module\Admin\Storage` as well

2021-10-04 12:21 UTC, MrPetovan commented
> @MrPetovan It wasn't **that** easy because of the dynamic option fetching and saving, so I had to adapt some parts of `Core\StorageManager` and `Module\Admin\Storage` as well

And yet you still enjoyed it, didn't you?

2021-10-04 13:31 UTC, MrPetovan requested changes

2021-10-04 13:31 UTC, MrPetovan commented on doc/AddonStorageBackend.md
> +All methods in the interface mus be implemented:
Isn't this a hard requirement for the class file to even parse after all?
```suggestion
All methods in the interface must be implemented:
```

2021-10-04 13:31 UTC, MrPetovan commented on doc/AddonStorageBackend.md
> +
Projecting much? 😄

Let's stay in the `samplestorage` addon context.

2021-10-04 13:31 UTC, MrPetovan commented on doc/Addons.md
> +	Hook::callAll('storage_config', $data);
Indentation 😉
```suggestion
    Hook::callAll('storage_config', $data);
```

2021-10-04 13:31 UTC, MrPetovan commented on src/Model/Storage/Filesystem.php
> +		$path           = $filesystemPath;
Shouldn't we check we have writing permission in the provided path?

2021-10-04 13:31 UTC, MrPetovan commented on doc/Addons.md
> +	Hook::callAll('storage_config', $data);
Additionally, please describe the hook, its input and output keys in the `$data` array earlier in this file.

2021-10-05 17:20 UTC, MrPetovan approved these changes

2021-10-05 17:21 UTC, MrPetovan commented
And how the tests are failing with the newly created Exception!

2021-10-05 17:46 UTC, nupplaphil commented
I love my tests :X :D

2021-10-05 18:41 UTC, MrPetovan approved these changes

2021-10-05 18:41 UTC, merged