[WIP] Migrate PermissionSet to Depository paradigm
friendica/friendica pull request #10836
Opened 2021-10-05 21:32 UTC by nupplaphil

FollowUp #10722 
A first draft for the new paradigm of the `PermissionSet`.

I need to test it, so it's WIP so far :-)

2021-10-05 22:28 UTC, MrPetovan requested changes
It looks good so far, you definitely got what I was getting at, I'm glad I'm not the only one in my mind anymore.

2021-10-05 22:28 UTC, MrPetovan commented on src/DI.php
> +use Friendica\Security\PermissionSet\Depository\PermissionSet;
Given the large number of single mentions for long namespaced classes, I've been avoiding import like this.
```suggestion
```

2021-10-05 22:28 UTC, MrPetovan commented on src/DI.php
>  	}
Please move the return type declaration to the language syntax now that we can:
```suggestion
	public static function permissionSetFactory(): \Friendica\Security\PermissionSet\Factory\PermissionSet
	{
		return self::$dice->create(\Friendica\Security\PermissionSet\Factory\PermissionSet::class);
	}
```

2021-10-05 22:28 UTC, MrPetovan commented on src/DI.php
> +		return self::$dice->create(PermissionSet::class);
```suggestion
		return self::$dice->create(\Friendica\Security\PermissionSet\Depository\PermissionSet::class);
```

2021-10-05 22:28 UTC, MrPetovan commented on src/DI.php
>  	public static function permissionSet()
```suggestion
	public static function permissionSet(): \Friendica\Security\PermissionSet\Depository\PermissionSet
```

2021-10-05 22:28 UTC, MrPetovan commented on src/DI.php
>  	 */
```suggestion
```

2021-10-05 22:28 UTC, MrPetovan commented on src/DI.php
>  	/**
```suggestion
```

2021-10-05 22:28 UTC, MrPetovan commented on src/Model/ProfileField.php
> +	/** @var \Friendica\Security\PermissionSet\Depository\PermissionSet */
Please use an import alias, like `PermissionSetDepository`. It should make the constructor declaration lighter on the eyes.

2021-10-05 22:28 UTC, MrPetovan commented on src/Model/ProfileField.php
> +				$this->permissionset = $this->permissionset ?? $this->permissionSetDepository->selectOneById($this->psid);
The previous code was checking for ownership, you need to maintain this feature parity with an additional check on the entity field value or in a separate Depository method.

2021-10-05 22:28 UTC, MrPetovan commented on src/Security/PermissionSet/Depository/PermissionSet.php
> +		];
Please move this to a private method since it's used twice for the same purpose.

2021-10-05 22:28 UTC, MrPetovan commented on src/Security/PermissionSet/Entity/PermissionSet.php
> +		$clone->id        = null;
Can you set protected members from here?

2021-10-05 22:28 UTC, MrPetovan commented on src/Security/PermissionSet/Factory/PermissionSet.php
> +		);
You can reuse `createFromTableRow` for this, passing the parameters in a row-like array.

2021-10-05 22:28 UTC, MrPetovan commented on src/Security/PermissionSet/Factory/PermissionSet.php
> +	public function createPrototypeForUser(int $uid, string $allowCid): Entity\PermissionSet
What is this meant for?

2021-10-07 17:05 UTC, nupplaphil commented on src/Model/ProfileField.php
> +	/** @var \Friendica\Security\PermissionSet\Depository\PermissionSet */
I know we already discussed it, but from my point of view, I generally would like to Postifx the Type to the class
- `PermissionSetDepository`
- `PermisisonSetFactory`
- ...

This would help us avoiding either aliases (which creates another translation layer between usage and class behind it) or using the full path :-/

But for now I use the alias :)

2021-10-07 17:06 UTC, nupplaphil commented on src/Model/ProfileField.php
> +				$this->permissionset = $this->permissionset ?? $this->permissionSetDepository->selectOneById($this->psid);
the check for ownership is "just" a security feature, isn't it? Because `id` should be unique

2021-10-07 17:24 UTC, MrPetovan commented on src/Model/ProfileField.php
> +				$this->permissionset = $this->permissionset ?? $this->permissionSetDepository->selectOneById($this->psid);
Indeed. It used to be part of the original query, so we need to either keep the same query, or add a separate check for ownership. I'd prefer the latter.

2021-10-07 17:51 UTC, nupplaphil commented on src/Model/ProfileField.php
> +				$this->permissionset = $this->permissionset ?? $this->permissionSetDepository->selectOneById($this->psid);
Hm .. I read it too late, so I added the uid field again .. so you think it would be better to fetch the PermissionSet and afterwards check against the local uid?

2021-10-07 17:52 UTC, nupplaphil commented on src/Security/PermissionSet/Entity/PermissionSet.php
> +		$clone->id        = null;
yep, I added a test as well for it to proove it :)

2021-10-07 17:52 UTC, nupplaphil commented on src/Security/PermissionSet/Factory/PermissionSet.php
> +	public function createPrototypeForUser(int $uid, string $allowCid): Entity\PermissionSet
I forgot to remove it, thx for the hint *g*

2021-10-07 17:53 UTC, MrPetovan commented on src/Model/ProfileField.php
> +				$this->permissionset = $this->permissionset ?? $this->permissionSetDepository->selectOneById($this->psid);
It allows us to throw different Exceptions for the two different cases, if it's embedded in the query we can't distinguish the cases. It's minor.

2021-10-07 17:55 UTC, nupplaphil commented on src/Model/ProfileField.php
> +				$this->permissionset = $this->permissionset ?? $this->permissionSetDepository->selectOneById($this->psid);
aaahh I see :-)

2021-10-07 18:53 UTC, nupplaphil commented
works:
![Bildschirmfoto vom 2021-10-07 20-51-56](https://user-images.githubusercontent.com/379654/136445052-e0e14b69-5939-444f-90ed-80281888bbb8.png)
That's the permissionSet behind it (last entry):
![Bildschirmfoto vom 2021-10-07 20-52-52](https://user-images.githubusercontent.com/379654/136445159-60d6fea3-67cd-4f5c-bfdc-938889104b28.png)

So "Ready for review"

2021-10-07 20:27 UTC, MrPetovan commented on src/Model/ProfileField.php
> +						throw new NotFoundException(sprintf('PermissionSet %d for ProfileSet %d is invalid.', $permissionSet->uid, $this->uid));
ProfileSet?

2021-10-08 11:07 UTC, MrPetovan commented on src/Model/ProfileField.php
> +						throw new NotFoundException(sprintf('PermissionSet %d for ProfileField %d is invalid.', $permissionSet->uid, $this->uid));
ProfileField? When the interpolated value is `uid`?

2021-10-08 11:34 UTC, nupplaphil commented on src/Model/ProfileField.php
> +						throw new NotFoundException(sprintf('PermissionSet %d for ProfileField %d is invalid.', $permissionSet->uid, $this->uid));
arg .. don't "quickfix" things you don't think about ..

2021-10-08 13:38 UTC, MrPetovan commented on src/Model/ProfileField.php
> +	/** @var \Friendica\Security\PermissionSet\Depository\PermissionSet */
The fact that we haven't had the use of an alias until now tells me we don't need to postfix all the classe names, and it makes the file tree a little bit easier on the eyes.

2021-10-08 13:39 UTC, MrPetovan approved these changes

2021-10-08 13:39 UTC, merged