`q` is now completely removed
friendica/friendica pull request #10857
Opened 2021-10-09 21:25 UTC by annando

One more file is removed from the `include` path.

2021-10-09 22:11 UTC, MrPetovan requested changes

2021-10-09 22:11 UTC, MrPetovan commented on src/Module/Search/Acl.php
> +	const TYPE_GLOBAL_CONTACT        = 'x'; //
?

2021-10-09 22:11 UTC, MrPetovan commented on src/Content/Widget.php
> +	public static function unavailableNetworksAsArray()
```suggestion
	public static function unavailableNetworks()
```

2021-10-09 22:11 UTC, MrPetovan commented on src/Content/Widget.php
> +	public static function unavailableNetworks()
```suggestion
	public static function unavailableNetworksCondition()
```
Why not return a `[condition, parameter]` condition?

2021-10-09 22:11 UTC, MrPetovan commented on src/Module/Search/Acl.php
> +			$condition = DBA::mergeConditions($condition, array_merge(["NOT `network` IN (" . substr(str_repeat("?, ", count($networks)), 0, -2) . ")"], $networks));
Isn’t this the same as `unavailableNetworks`?

2021-10-10 05:40 UTC, annando commented on src/Module/Search/Acl.php
> +			$condition = DBA::mergeConditions($condition, array_merge(["NOT `network` IN (" . substr(str_repeat("?, ", count($networks)), 0, -2) . ")"], $networks));
`unavailableNetworksAsArray` is returning the networks as array while `unavailableNetworks` is returning a part of a SQL query.

2021-10-10 14:53 UTC, MrPetovan commented on src/Module/Search/Acl.php
> +			$condition = DBA::mergeConditions($condition, array_merge(["NOT `network` IN (" . substr(str_repeat("?, ", count($networks)), 0, -2) . ")"], $networks));
And this looks like it's returning a part of an SQL query about unavailable networks, the same function as `unavailableNetworks`.

2021-10-10 20:07 UTC, annando commented on src/Module/Search/Acl.php
> +			$condition = DBA::mergeConditions($condition, array_merge(["NOT `network` IN (" . substr(str_repeat("?, ", count($networks)), 0, -2) . ")"], $networks));
No. The one returns a string with the complete query (that also contains the values) and the new one returns an array with the query with the placeholders and the values in separate array elements.

2021-10-10 20:08 UTC, annando commented on src/Content/Widget.php
> +	public static function unavailableNetworks()
I wanted to make this the most generic usable at the moment. We can always change this anytime if needed.

2021-10-10 22:39 UTC, MrPetovan commented on src/Module/Search/Acl.php
> +			$condition = DBA::mergeConditions($condition, array_merge(["NOT `network` IN (" . substr(str_repeat("?, ", count($networks)), 0, -2) . ")"], $networks));
Why not make the `unavailableNetworks` method return the SQL condition array replace this line with it ? Currently it looks like the same feature is duplicated in two very separate locations.

2021-10-11 03:16 UTC, annando commented on src/Module/Search/Acl.php
> +			$condition = DBA::mergeConditions($condition, array_merge(["NOT `network` IN (" . substr(str_repeat("?, ", count($networks)), 0, -2) . ")"], $networks));
The function is used at several places. In a next iteration we can have a look at the other places as well.

2021-10-11 03:40 UTC, MrPetovan approved these changes

2021-10-11 03:40 UTC, merged