Move Introduction to Depository Paradigm
friendica/friendica pull request #10893
Opened 2021-10-18 20:51 UTC by nupplaphil

FollowUp #10860

2021-10-18 23:03 UTC, MrPetovan commented on src/Contact/Introduction/Entity/Introduction.php
> +	public function setIgnore()
I'd rather we use use case verbs for Entity methods. Rather than explicitly "setting" a field, I'd prefer if we acted on the Entity directly. In this case it would just be 
```suggestion
	public function ignore()
```

2021-10-18 23:03 UTC, MrPetovan commented on src/Contact/Introduction/Entity/Introduction.php
> +}
I'm surprised to not see the `block()` method?

2021-10-19 19:05 UTC, nupplaphil commented on src/Contact/Introduction/Entity/Introduction.php
> +}
@MrPetovan / @annando - I'm not even sure where we're using the `'blocked'` column.. We only set it to false at the beginning and never update/uset it anymore .. I don't find any reference at the codebase

2021-10-19 19:20 UTC, MrPetovan requested changes

2021-10-19 19:20 UTC, MrPetovan commented on src/Contact/Introduction/Entity/Introduction.php
> +}
Fair enough, can you please mark it as deprecated in the database structure comment and remove the field from the Entity with all the current references to it (Factory, Depository...).

2021-10-19 19:33 UTC, MrPetovan requested changes

2021-10-19 19:33 UTC, MrPetovan commented on doc/database/db_intro.md
> +| blocked     | deprecated        | boolean            | NO   |     | 1                   |                |
Please update de default value here as well.

2021-10-19 19:33 UTC, MrPetovan approved these changes

2021-10-19 20:42 UTC, MrPetovan commented on src/Contact/Introduction/Factory/Introduction.php
> +		int $sid,
No more default `null` value?

2021-10-19 21:01 UTC, nupplaphil commented on src/Contact/Introduction/Factory/Introduction.php
> +		int $sid,
aahh .. I changed the wrong contact reference, thx :D ..

2021-10-21 19:52 UTC, MrPetovan approved these changes

2021-10-21 20:08 UTC, MrPetovan approved these changes

2021-10-21 20:14 UTC, nupplaphil commented
Done :)

Fixed some issues outside of this scope as well

2021-10-21 20:15 UTC, MrPetovan approved these changes

2021-10-21 20:20 UTC, MrPetovan approved these changes

2021-10-21 20:26 UTC, merged