Replace deprecated `log` calls
friendica/friendica pull request #10908
Opened 2021-10-20 18:55 UTC by annando

Several `log` calls have been replaced. To reduce the amount of files this PR will have a following one with the rest.

2021-10-20 20:28 UTC, MrPetovan requested changes
I've suggested some logger severity changes. Here are my guidelines:
- `info`: Expected successful code path
- `notice`: Expected unsuccessful code path
- `warning`: Unexpected unsuccessful code path
- `critical`: Crippling Friendica capabilities

2021-10-20 20:28 UTC, MrPetovan commented on mod/pubsub.php
> +	Logger::notice('Feed arrived from ' . $_SERVER['REMOTE_ADDR'] . ' for ' .  DI::args()->getCommand() . ' with user-agent: ' . $_SERVER['HTTP_USER_AGENT']);
```suggestion
	Logger::info('Feed arrived from ' . $_SERVER['REMOTE_ADDR'] . ' for ' .  DI::args()->getCommand() . ' with user-agent: ' . $_SERVER['HTTP_USER_AGENT']);
```

2021-10-20 20:28 UTC, MrPetovan commented on mod/pubsub.php
> +	Logger::notice('Import item for ' . $nick . ' from ' . $contact['nick'] . ' (' . $contact['id'] . ')');
```suggestion
	Logger::info('Import item for ' . $nick . ' from ' . $contact['nick'] . ' (' . $contact['id'] . ')');
```

2021-10-20 20:28 UTC, MrPetovan commented on mod/pubsubhubbub.php
> +		Logger::notice("$hub_mode request from " . $_SERVER['REMOTE_ADDR']);
```suggestion
		Logger::info("$hub_mode request from " . $_SERVER['REMOTE_ADDR']);
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Model/Contact.php
> +				Logger::notice('share returns: ' . $ret);
```suggestion
				Logger::info('share returns: ' . $ret);
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Model/Contact.php
> +				Logger::notice('Follow returns: ' . $ret);
```suggestion
				Logger::info('Follow returns: ' . $ret);
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Model/Contact.php
> +			Logger::notice('update_contact_birthday: ' . $contact['bd']);
```suggestion
			Logger::info('update_contact_birthday: ' . $contact['bd']);
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Model/Item.php
> +		Logger::notice('User ' . $uid . ": expired $expired items; expire items: $expire_items, expire notes: $expire_notes, expire starred: $expire_starred, expire photos: $expire_photos");
```suggestion
		Logger::info('User ' . $uid . ": expired $expired items; expire items: $expire_items, expire notes: $expire_notes, expire starred: $expire_starred, expire photos: $expire_photos");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +		Logger::notice("Processing mails");
```suggestion
		Logger::info("Processing mails");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +		Logger::notice("Processing relocations");
```suggestion
		Logger::info("Processing relocations");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +		Logger::notice('Contacts are updated.');
```suggestion
		Logger::info('Contacts are updated.');
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +				Logger::notice("possible community action");
```suggestion
				Logger::info("possible community action");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +				Logger::notice("not a community action");
```suggestion
				Logger::info("not a community action");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +				Logger::notice("New follower");
```suggestion
				Logger::info("New follower");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +				Logger::notice("Lost follower");
```suggestion
				Logger::info("Lost follower");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +				Logger::notice("New friend request");
```suggestion
				Logger::info("New friend request");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +				Logger::notice("Lost sharer");
```suggestion
				Logger::info("Lost sharer");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +		Logger::notice("Processing entries");
```suggestion
		Logger::info("Processing entries");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +		Logger::notice("Processing deletions");
```suggestion
		Logger::info("Processing deletions");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/DFRN.php
> +					Logger::notice('mention found: ' . $mtch[2]);
```suggestion
					Logger::info('mention found: ' . $mtch[2]);
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/OStatus.php
> +							Logger::notice("Item with uri ".$item["uri"]." for user ".$importer["uid"].' stored. Return value: '.$ret);
```suggestion
							Logger::info("Item with uri ".$item["uri"]." for user ".$importer["uid"].' stored. Return value: '.$ret);
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/OStatus.php
> +							Logger::info("Item with uri ".$item["uri"]." is from a blocked contact.");
```suggestion
							Logger::notice("Item with uri ".$item["uri"]." is from a blocked contact.");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/OStatus.php
> +							Logger::info("Item with uri ".$item["uri"]." for user ".$importer["uid"]." already exists.");
```suggestion
							Logger::notice("Item with uri ".$item["uri"]." for user ".$importer["uid"]." already exists.");
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/Salmon.php
> +		Logger::notice('Fetching salmon key for '.$uri);
```suggestion
		Logger::info('Fetching salmon key for '.$uri);
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/Salmon.php
> +		Logger::notice('slapper called for '.$url.'. Data: ' . $slap);
```suggestion
		Logger::info('slapper called for '.$url.'. Data: ' . $slap);
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Protocol/Salmon.php
> +		Logger::notice('slapper for '.$url.' returned ' . $return_code);
```suggestion
		Logger::info('slapper for '.$url.' returned ' . $return_code);
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Util/DateTimeFormat.php
> +			Logger::notice('DateTimeFormat::convert: exception: ' . $e->getMessage());
```suggestion
			Logger::warning('DateTimeFormat::convert: exception: ' . $e->getMessage());
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Util/XML.php
> +			Logger::notice('Xml::toArray: parser function missing');
```suggestion
			Logger::critical('Xml::toArray: parser function missing');
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Util/XML.php
> +			Logger::notice('Xml::toArray: xml_parser_create: no resource');
```suggestion
			Logger::warning('Xml::toArray: xml_parser_create: no resource');
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Worker/CheckVersion.php
> +		Logger::notice('checkversion: start');
```suggestion
		Logger::info('checkversion: start');
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Worker/CheckVersion.php
> +		Logger::notice("Upstream VERSION is: ".$gitversion);
```suggestion
		Logger::info("Upstream VERSION is: ".$gitversion);
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Worker/CheckVersion.php
> +		Logger::notice('checkversion: end');
```suggestion
		Logger::info('checkversion: end');
```

2021-10-20 20:28 UTC, MrPetovan commented on src/Worker/PubSubPublish.php
> +			Logger::notice('Successfully pushed to ' . $subscriber['callback_url']);
```suggestion
			Logger::info('Successfully pushed to ' . $subscriber['callback_url']);
```

2021-10-20 20:28 UTC, MrPetovan commented on view/theme/frio/theme.php
> +	Logger::notice('installed theme frio');
```suggestion
	Logger::info('installed theme frio');
```

2021-10-20 21:45 UTC, nupplaphil commented
Didn't you miss error, do you?

There's a official guideline with examples here: https://github.com/php-fig/log/blob/master/src/LoggerInterface.php

This is how I set the levels

2021-10-21 01:48 UTC, MrPetovan commented
I did miss the `error` level indeed but the way it's worded sounds like the PHP Notice and Warnings that are currently logged separately.

2021-10-21 02:48 UTC, annando commented
I decide between `info` and `notice` mostly by volume. Means: for a process like the receiving of a message I want to have a full trace of processes with `info`. But with `notice` I want have some bread crumbs. Means I want to at least have some information that a message arrived. One should say that with `notice` I want to see *if* the system is working and with `info`I want to see *how* it is working.

2021-10-21 03:05 UTC, MrPetovan commented
This is pretty much what I said with `info` and `debug` for the detailed how. The simply guidelines I suggested were inspired by the existing examples, it just isn't applied consistently.

2021-10-21 09:29 UTC, annando commented
When we are reconsidering where to use which log levels, we shouldn't do this only for this few legacy `log` calls but for all the `notice` calls that are out there. Also we then had to consider move several `info` calls to `debug`.

2021-10-21 11:20 UTC, MrPetovan commented
So you won't accept my suggestions in this PR?

2021-10-21 16:53 UTC, annando commented
I don't know. One the one hand I see that we have to have a deep look at what messages we expect at which log levels. On the other hand moving several log messages from "notice" to "info" can lead in losing important log messages for regular servers that currently will most likely run with "notice" because "info" is too crowded. (But on the other hand I don't want to make your contribution to this PR obsolete)

2021-10-21 17:06 UTC, MrPetovan commented
Thank you for your consideration! What are the important messages that I downgraded from `notice` to `info`? I didn't change that many calls, it should be easy to spot the important calls that need to stay at the `notice` level.

2021-10-22 07:58 UTC, annando commented
I will have a look at the suggestions, I guess.

2021-10-25 19:30 UTC, annando commented on src/Protocol/DFRN.php
> +		Logger::notice("Processing mails");
I would like to keep that. It is important for tracing incoming messages.

2021-10-25 19:30 UTC, annando commented on src/Protocol/DFRN.php
> +		Logger::notice("Processing relocations");
Like above. It is important for tracing incoming messages.

2021-10-25 20:08 UTC, MrPetovan approved these changes

2021-10-25 20:08 UTC, merged