Move FSuggest to new paradigm
friendica/friendica pull request #10911
Opened 2021-10-21 21:20 UTC by nupplaphil

Soo .. this is the last "old" Repository class.

The last commit is the renaming from "Depository" to "Repository" again because we don't need the distinguishing any more :)

2021-10-22 12:52 UTC, MrPetovan commented
I was getting used to `Depository` 😢

2021-10-22 13:08 UTC, nupplaphil commented
Ah ok sry, I thought it was just temporary.. It's the first time I hear this word, so I thought relying to known names will lead to a better understanding of the patterns .. I'd prefer it, but I'm not dogmatic about it

2021-10-22 13:16 UTC, MrPetovan commented
It was a joke, I'm fine with either. I found `Depository` looking for synonyms of `Repository`.

2021-10-22 19:41 UTC, MrPetovan commented on tests/src/Contact/FriendSuggest/Factory/FriendSuggestTest.php
> +	public function assertFriendSuggest(Entity\FriendSuggest $friendSuggest, array $assertion)
Traditionally in `assert*` method, the assertion value is the first parameter. You can see it in the following `assertEquals` calls in this method.
```suggestion
	public function assertFriendSuggest(array $assertion, Entity\FriendSuggest $friendSuggest)
```

2021-10-22 19:41 UTC, MrPetovan commented on tests/src/Contact/FriendSuggest/Factory/FriendSuggestTest.php
> +				],
Instead of an arbitrary array, why not using the shiny Entity data structure and its extensive constructor?

2021-10-22 19:55 UTC, nupplaphil commented
aaand done :)

2021-10-22 21:17 UTC, MrPetovan requested changes

2021-10-22 21:17 UTC, MrPetovan commented on src/Contact/FriendSuggest/Exception/FriendSuggestNotFoundException.php
> +	public function __construct($message = "", \Throwable $previous = null)
Quote style.
```suggestion
	public function __construct($message = '', \Throwable $previous = null)
```

2021-10-22 21:17 UTC, MrPetovan commented on src/Contact/FriendSuggest/Exception/FriendSuggestPersistenceException.php
> +	public function __construct($message = "", \Throwable $previous = null)
```suggestion
	public function __construct($message = '', \Throwable $previous = null)
```

2021-10-22 21:17 UTC, MrPetovan commented on src/Contact/FriendSuggest/Repository/FriendSuggest.php
> +				return $this->factory->createFromTableRow($fields);
I would also do a `return $this->selectOneById($this->db->lastInsertId());` in this case since we can't know what transformation the database will operate during the update.

2021-10-23 07:48 UTC, nupplaphil commented on src/Contact/FriendSuggest/Repository/FriendSuggest.php
> +				return $this->factory->createFromTableRow($fields);
I won't do that. AFAIK, the `lastInsertId()` does return the last **inserted** id. Since we update it, we would return the wrong id, would we?

2021-10-23 13:43 UTC, MrPetovan commented on src/Contact/FriendSuggest/Repository/FriendSuggest.php
> +				return $this->factory->createFromTableRow($fields);
You're right, it should be
```suggestion
				return $this->selectOneById($fsuggest->id);
```

2021-10-23 17:50 UTC, nupplaphil commented
Draft mode again --> I found a bug during the fsuggest worker execution

2021-10-23 18:23 UTC, nupplaphil commented
done .. the worker didn't work as expected, it seems I mixed app (this branch) & cron (develop) ;-)

2021-10-24 02:01 UTC, MrPetovan commented
Warning: I rebased your branch onto `develop` to satisfy the recent `messages.po` update that was triggering a merge conflict. Please be mindful of this next time you pull your local clone of your own Friendica fork repository.

2021-10-24 02:04 UTC, MrPetovan approved these changes

2021-10-24 02:04 UTC, merged