Paradigm Restructuring Part 1 - Core classes
friendica/friendica pull request #10918
Opened 2021-10-23 10:29 UTC by nupplaphil

FollowUp #10911 
Addons: https://github.com/friendica/friendica-addons/pull/1195

Merge all code-parts of the core capabilities into each specific folder, as the new paradigm says :-)
I do find this new way better and try to follow it with the code parts I created so far

- Restructuring Cache
- Restructuring (P)Config
- Restructuring Lock
- Restructuring Session

2021-10-24 17:17 UTC, nupplaphil commented
@MrPetovan - the folder structure for a Domain (Config/Cache/..):
- `Factory` ... The factories for this domain
- `Type` ... The subtypes of the given Domain (childs of the overall domain, like `ApcuCache` or `JitConfig`)
- `Enum` ... Classes replacing ENUM capabilities in PHP
- `Cache` ... a Sub-Domain of `Config` or `PConfig` for the Caching mechanism of the Domain
-  `Model` ... Service-like Business Logic (maybe part of an entity in a more mature codebase)

I used this structure for all other PRs as well

2021-10-25 02:38 UTC, MrPetovan reviewed
Nice work! I'm still not a fan of repeating what a class is in its name if it's already in the namespace path (like `Cache/Factory/CacheFactory.php`) but I guess it can't hurt.

On the other hand I'd really like us to have interfaces describe capabilities in their name like I started doing with `ICanCreateFromTableRow`.

2021-10-25 02:38 UTC, MrPetovan commented on src/Core/Config/Model/DbaUtils.php
> +class DbaUtils
Why not use the `Util` namespace?
```suggestion
namespace Friendica\Core\Config\Util;

class ValueConversion
```

2021-10-25 02:38 UTC, MrPetovan commented on src/Core/Lock/ILock.php
>   * Lock Interface
While we are moving stuff around, why not rename this interface to a meaningful capability name like `ICanHandleLocks`?

2021-10-25 02:38 UTC, MrPetovan commented on src/Core/PConfig/Cache/Cache.php
> +namespace Friendica\Core\PConfig\Cache;
I'm not sure I understand the purpose of this particular namespace, it feels redundant with the class name?

2021-10-25 17:41 UTC, nupplaphil commented
> Nice work! I'm still not a fan of repeating what a class is in its name if it's already in the namespace path (like `Cache/Factory/CacheFactory.php`) but I guess it can't hurt.

It's redundant at any case I think:
`Cache\Factory\Cache` or `Cache\Factory\CacheFactory`
The reason I'm using the latter is that I can be sure that I can fully include this class per `use` inside another class without scrolling to the `use` block to see which Type of class I'm currently using (`Factory\Cache`, `Entity\Cache`, ..). It's making the name unique in it's usage. And than I'd say `Entity` is the only class type without any postfix, so every time I use a `Cache`, I can be sure to use the entity.

That's my background ^^.. If you don't agree or not fully agree, I'll rename the classes to be as homogeneous as possible at our codebase

2021-10-25 17:58 UTC, MrPetovan commented
My personal opinion is that I can use namespace aliases to resolve local ambiguity inside the same file, like `use Config\Factory\Cache as CacheFactory;`. As a result, I don't have to use the longer names when not compelled to.

But I also remember @annando saying it was easier to find the file name if it was more descriptive by itself so I feel outnumbered, and I don't have a strong opinion about either way.

2021-10-26 19:58 UTC, nupplaphil commented
I changed WAY too much in this PR .. At least local is everything still fine, I'll run it at my friendica.philipp.info node for a while.

But I didn't change any behavior, I "just" added all the type-hints and Exception-handlings around it (so a regression may be possible for example in cases where we use these classes with invalid parameters).

Two things:
- I still followed your pattern for Factory/Repository - I think it's up to @annando if he likes a namespace\class like `Cache\Repository\Cache` or `Cache\Repository\CacheRepository`
- I'm not very comfortable with the way we use interfaces. I'd prefer to distinguish between capability interfaces (like `Countable` or `Seriazable`) and typed interfaces (like `Lock` or `Cache`). I feel like the current naming convention could worry people (tbh I struggled finding a good name for interfaces and if someone doesn't really feel the need for it, it may lead to strange names ^^)

2021-10-26 19:58 UTC, MrPetovan requested changes

2021-10-26 19:58 UTC, MrPetovan commented on src/App.php
> +	 * @param \Friendica\Core\PConfig\Capability\IManagePersonalConfigValues $pConfig  Personal configuration
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/App/BaseURL.php
> +	 * @param \Friendica\Core\Config\Capability\IManageConfigValues $config The Friendica IConfiguration
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/App/Module.php
> +	 * @param \Friendica\Core\Config\Capability\IManageConfigValues $config The Friendica Configuration
You can use `Core\Config\Capability\IManageConfigValues` since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/App/Page.php
> +	 * @param \Friendica\Core\PConfig\Capability\IManagePersonalConfigValues $pConfig The Friendica personal configuration (for user)
You can use the shorthands since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Console/Lock.php
> +	 * @var \Friendica\Core\Lock\Capability\ICanLock
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Console/PostUpdate.php
> +	 * @var \Friendica\Core\Config\Capability\IManageConfigValues
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Factory/LoggerFactory.php
> +	 * @param \Friendica\Core\Config\Capability\IManageConfigValues $config     The config
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Factory/LoggerFactory.php
> +	 * @param \Friendica\Core\Config\Capability\IManageConfigValues $config     The config
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Model/Storage/FilesystemConfig.php
> +	 * @param \Friendica\Core\Config\Capability\IManageConfigValues $config
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Model/User/Cookie.php
> +	 * @param \Friendica\Core\Config\Capability\IManageConfigValues $config
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Navigation/Notifications/Factory/Introduction.php
> +	/** @var \Friendica\Core\PConfig\Capability\IManagePersonalConfigValues */
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Navigation/Notifications/Factory/Introduction.php
> +	/** @var \Friendica\Core\Session\Capability\IHandleSessions */
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Navigation/Notifications/Repository/Notify.php
> +	/** @var \Friendica\Core\Config\Capability\IManageConfigValues */
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Security/Authentication.php
> +	/** @var \Friendica\Core\Session\Capability\IHandleSessions */
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Security/Authentication.php
> +	 * @param \Friendica\Core\Session\Capability\IHandleSessions $session
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Security/ExAuth.php
> +	 * @param \Friendica\Core\PConfig\Capability\IManagePersonalConfigValues $pConfig
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Util/Emailer.php
> +	/** @var \Friendica\Core\Config\Capability\IManageConfigValues */
You can use the shorthand since there is a `use` statement.

2021-10-26 19:58 UTC, MrPetovan commented on src/Util/Emailer.php
> +	/** @var \Friendica\Core\PConfig\Capability\IManagePersonalConfigValues */
You can use the shorthand since there is a `use` statement.

2021-10-27 17:20 UTC, nupplaphil commented
So far, so good .. worker works, app applicable
I tried posting, twitter addon, all settings I know so far

2021-10-27 17:45 UTC, MrPetovan approved these changes

2021-10-27 17:45 UTC, merged

2021-10-27 17:45 UTC, MrPetovan commented
Don't worry, we'll find something to fix.

2021-10-27 17:49 UTC, nupplaphil commented
@MrPetovan - plz don't forget https://github.com/friendica/friendica-addons/pull/1195