Paradigm Restructuring Part 2 - Storage
friendica/friendica pull request #10919
Opened 2021-10-23 10:29 UTC by nupplaphil

FollowUp #10918 
Addons: https://github.com/friendica/friendica-addons/pull/1196

- Storage restructuring

2021-10-27 18:07 UTC, MrPetovan requested changes

2021-10-27 18:07 UTC, MrPetovan commented on src/Console/Storage.php
> +	/** @var \Friendica\Core\Storage\Repository\StorageManager */
Extraneous absolute path
```suggestion
	/** @var StorageManager */
```

2021-10-27 18:07 UTC, MrPetovan commented on src/Core/Storage/Capability/ICanReadFromStore.php
> +interface ICanReadFromStore
This is so much better!

2021-10-27 18:07 UTC, MrPetovan commented on src/Core/Storage/Repository/StorageManager.php
> +							$this->logger->info('Deleted data from old backend.', ['oldBackend' => $source, 'oldReference' => $sourceRef]);
Why the change of tense?

2021-10-27 18:07 UTC, MrPetovan commented on src/Module/Admin/Storage.php
> +			/** @var \Friendica\Core\Storage\Capability\ICanConfigureStorage|false $newStorageConfig */
Extraneous absolute name:
```suggestion
			/** @var ICanConfigureStorage|false $newStorageConfig */
```

2021-10-27 18:07 UTC, MrPetovan commented on src/Module/Admin/Storage.php
> +				/** @var \Friendica\Core\Storage\Capability\ICanWriteToStorage $newstorage */
Extraneous absolute name:
```suggestion
				/** @var ICanWriteToStorage $newstorage */
```

2021-10-27 18:07 UTC, MrPetovan commented on tests/src/Core/Storage/StorageConfigTest.php
> +	/** @return \Friendica\Core\Storage\Capability\ICanConfigureStorage */
Extraneous absolute name:
```suggestion
	/** @return ICanConfigureStorage */
```

2021-10-27 18:07 UTC, MrPetovan commented on tests/src/Core/Storage/StorageConfigTest.php
> +	abstract protected function assertOption(\Friendica\Core\Storage\Capability\ICanConfigureStorage $storage);
Extraneous absolute name:
```suggestion
	abstract protected function assertOption(ICanConfigureStorage $storage);
```

2021-10-27 18:11 UTC, nupplaphil commented on src/Core/Storage/Repository/StorageManager.php
> +							$this->logger->info('Deleted data from old backend.', ['oldBackend' => $source, 'oldReference' => $sourceRef]);
tbh .. My PHPStorm all the time complains about the non-conform SQL-language and I don't find a switch to ignore it in this case :D

2021-10-27 18:38 UTC, MrPetovan approved these changes

2021-10-28 14:10 UTC, nupplaphil commented
looks good, my node works (even with webdav addon :) )

2021-10-28 14:12 UTC, merged