Add event timezone in Model\Event::getHTML
friendica/friendica pull request #10917
Opened 2021-10-23 04:20 UTC by MrPetovan

Removes the ambiguity described in #10914 

Also fixes a long-standing issue accessing backend modules with an existing session with 2FA activated.

2021-10-23 08:22 UTC, nupplaphil approved these changes

2021-10-23 08:24 UTC, nupplaphil requested changes

2021-10-23 08:24 UTC, nupplaphil commented on view/lang/C/messages.po
> +msgid "l F d, Y \\@ g:i A"
Is it intended that you don't change this Datetime patterns as well?

2021-10-23 14:28 UTC, MrPetovan commented on view/lang/C/messages.po
> +msgid "l F d, Y \\@ g:i A"
It isn't intended so much as "overlooked". Since it isn't used in event display in feeds, I didn't know it was there.

2021-10-23 17:48 UTC, annando commented on src/Model/Event.php
> +		$bd_format = DI::l10n()->t('l F d, Y \@ g:i A \G\M\T'); // Friday January 18, 2011 @ 8 AM.
Can you update the example as well?

2021-10-23 20:13 UTC, MrPetovan commented on view/lang/C/messages.po
> +msgid "l F d, Y \\@ g:i A"
After looking into both places, they are meant to show local time and as such do not need to be updated.

2021-10-23 20:13 UTC, MrPetovan commented on src/Model/Event.php
> +		$bd_format = DI::l10n()->t('l F d, Y \@ g:i A \G\M\T'); // Friday January 18, 2011 @ 8 AM.
Done.

2021-10-24 06:53 UTC, tobiasd commented on src/Model/Event.php
> +		$bd_format = DI::l10n()->t('l F d, Y \@ g:i A \G\M\T'); // Friday January 18, 2011 @ 8 AM.
And does this translate the timezone into the correct local time or will the users have to ask their fav. search engine to translate the times?

2021-10-24 14:28 UTC, nupplaphil approved these changes

2021-10-25 03:24 UTC, MrPetovan commented
After reviewing the usage more carefully, I found out that this format is used in a localized time string, so it is using a potentially variable timezone. I added this information since it can be the timezone of the server itself.

2021-10-25 04:33 UTC, merged