Add extended ErrorHandling
friendica/friendica pull request #10923
Opened 2021-10-23 18:50 UTC by nupplaphil

During my logger refactoring, I found a ErrorHandler at monolog here: https://github.com/Seldaek/monolog/blob/main/src/Monolog/ErrorHandler.php

As far as I can read, the MIT License allows us to use it as well. I copied the code and adapted it for Friendica.

The result is that we can now even log WSOD errors:
```console
2021-10-23T18:41:49Z index [ERROR]: Uncaught Exception Error: "Call to undefined method Friendica\App::getBaseath()" at /vagrant/src/App.php line 351 {"exception":"Error: Call to undefined method Friendica\\App::getBaseath() in \/vagrant\/src\/App.php:351\nStack trace:\n#0 \/vagrant\/src\/App.php(332): Friendica\\App->load()\n#1 [internal function]: Friendica\\App->__construct()\n#2 \/vagrant\/vendor\/level-2\/dice\/Dice.php(132): ReflectionMethod->invokeArgs()\n#3 \/vagrant\/vendor\/level-2\/dice\/Dice.php(96): Dice\\Dice->Dice\\{closure}()\n#4 \/vagrant\/src\/DI.php(62): Dice\\Dice->create()\n#5 \/vagrant\/index.php(39): Friendica\\DI::app()\n#6 {main}"} - {"file":null,"line":null,"function":null,"uid":"b40781","process_id":114528}
```

2021-10-23 19:18 UTC, annando commented
What will happen when there was a fatal error during the handling of a fatal error?

2021-10-23 20:40 UTC, nupplaphil commented
tbh I don't know, but I think the worst thing is that the exception will be handled like before :D

2021-10-24 02:16 UTC, MrPetovan requested changes

2021-10-24 02:16 UTC, MrPetovan commented on src/Core/Logger/Handler/ErrorHandler.php
> +	public function registerExceptionHandler(array $levelMap = [], bool $callPrevious = true): self
Second parameter isn't documented

2021-10-24 02:16 UTC, MrPetovan commented on src/Core/Logger/Handler/ErrorHandler.php
> +	public function registerErrorHandler(array $levelMap = [], bool $callPrevious = true, int $errorTypes = -1, bool $handleOnlyReportedErrors = true): self
Parameters beyond the first aren't documented.

2021-10-24 17:45 UTC, nupplaphil commented
bang .. found my first E_WARNING with docker:
```console
2021-10-24T17:38:26Z console [WARNING]: E_WARNING: session_write_close(): Failed to write session data using user defined save handler. (session.save_path: ) {"code":2,"message":"session_write_close(): Failed to write session data using user defined save handler. (session.save_path:
)","file":"Unknown","line":0} - {"file":null,"line":null,"function":"session_write_close","uid":"5ee1c2","process_id":53}```

2021-10-25 02:41 UTC, MrPetovan approved these changes
I like this, making us of our internal logging levels.

2021-10-25 02:41 UTC, merged