Paradigm Restructuring Part 3 - Logger & HTTPClient
friendica/friendica pull request #10921
Opened 2021-10-23 10:54 UTC by nupplaphil

FollowUp #10919 
Addons: https://github.com/friendica/friendica-addons/pull/1198

- Restructuring Logger
- Restructuring HTTPClient

2021-10-28 18:01 UTC, nupplaphil commented
I think this one can get merged as well
- Logger logs (Worker, normal app) like before
- I already fetched posts 
- I already see curl redirects inside the log

2021-10-28 19:15 UTC, MrPetovan requested changes

2021-10-28 19:15 UTC, MrPetovan commented on src/Core/Logger/Factory/Logger.php
> +		'Friendica\\Core\\Logger\\Type\\Monolog',
Please use the `::class` magic constant for these:
```suggestion
		\Friendica\Core\Logger\Type::class,
		\Friendica\Core\Logger\Type\Monolog::class,
```

2021-10-28 19:15 UTC, MrPetovan commented on src/Core/Logger/Factory/Logger.php
> +						/// @todo isn't it possible to give the admin any hint about this wrong configuration?
I think we can default to `Syslog` instead?

2021-10-28 19:15 UTC, MrPetovan commented on src/Network/HTTPClient/Capability/ICanRequestPerHttp.php
> +interface ICanRequestPerHttp
"per"? It sounds odd to my American English-trained ear. How about one of these alternatives:
```suggestion
interface ICanPerformHttpRequests
```
```suggestion
interface ICanIssueHttpRequests
```
```suggestion
interface ICanSendHttpRequests
```
I
I'm partial to the latter, we already use the verb `send` in the phpDoc.

2021-10-28 19:15 UTC, MrPetovan commented on src/Network/HTTPClient/Client/HttpClientCan.php
> +class HttpClientCan implements ICanRequestPerHttp
`HttpClientCan`? Like a tin can 🥫?

2021-10-28 21:38 UTC, nupplaphil commented on src/Core/Logger/Factory/Logger.php
> +		'Friendica\\Core\\Logger\\Type\\Monolog',
This works even if there is no class?

2021-10-28 21:43 UTC, nupplaphil commented on src/Network/HTTPClient/Capability/ICanRequestPerHttp.php
> +interface ICanRequestPerHttp
A little bit too denglish :D

2021-10-28 23:25 UTC, MrPetovan commented on src/Core/Logger/Factory/Logger.php
> +		'Friendica\\Core\\Logger\\Type\\Monolog',
Or, they are meant as prefixes? In this case the second line is superfluous as it is included in the more general prefix defined before.
```suggestion
		'Friendica\Core\Logger\Type',
```

2021-10-29 06:06 UTC, nupplaphil commented on src/Core/Logger/Factory/Logger.php
> +						/// @todo isn't it possible to give the admin any hint about this wrong configuration?
I added it with another try/catch block :D .. The only real problem would be, if we set an invalid minimum level, so we would get argument exceptions at any case.

=> Shall I create a fallback min-level in that case?

2021-10-29 13:56 UTC, MrPetovan approved these changes

2021-10-29 13:56 UTC, merged