Replace Module::init() with Constructors
friendica/friendica pull request #10994
Opened 2021-11-17 21:21 UTC by nupplaphil

FollowUp #10977 
Addresses feedback https://github.com/friendica/friendica/pull/10977#discussion_r748934818

All `Module::init()` methods are now replaced with the `__constructor()` method and directly uses now Depdency Injection per constructor. So no `DI::` calls are now necessary inside the Module classes anymore.

2021-11-18 16:14 UTC, MrPetovan requested changes

2021-11-18 16:14 UTC, MrPetovan commented on src/Module/BaseNotifications.php
>  		$tabs = self::getTabs();
Do you intend on furthering the refactoring in this method? I spot at least `DI::l10n()` call.

2021-11-18 16:14 UTC, MrPetovan commented on src/BaseModule.php
> +		$this->l10n       = $l10n;
Since `L10n` is now a shared dependency of `BaseModule`, I'd like to have local wrappers for the translation methods in order to simplify further the `DI::l10n()->t` calls into `$this->t` calls in modules.

2021-11-18 16:14 UTC, MrPetovan commented on src/Module/Profile/Index.php
> +
Redundant.
```suggestion
```

2021-11-18 16:14 UTC, MrPetovan commented on src/Module/RemoteFollow.php
> +		$page['aside'] = Widget\VCard::getHTML($this->owner);
This is only relevant in the `content()` method.

2021-11-18 21:29 UTC, MrPetovan approved these changes

2021-11-19 00:21 UTC, merged

2021-11-19 11:05 UTC, AlfredSK commented
Looks like this PR breaks the possibility to write new posts. Even the preview doesn't work. I'm using frio.

2021-11-19 11:07 UTC, copiis commented
> Looks like this PR breaks the possibility to write new posts. Even the preview doesn't work. I'm using frio.

I can confirm

2021-11-19 12:24 UTC, MrPetovan commented
This PR has now been reverted.