Module Fixings&FollowUps
friendica/friendica pull request #11044
Opened 2021-11-28 13:39 UTC by nupplaphil

- Make `$_REQUEST` processing independent of sub-calls
- Make `HTTPInputData`dynamic (for better testability)
- Make API call permission checks more reliable (no more forced to call the corresponding `parent::`)

Bugfixings:
- [ ] 11023

2021-11-28 13:41 UTC, nupplaphil commented on src/App.php
> +			$response = $module->run($input);
@annando - Here's the PHP Input stream processing now. It's called **before** any sub-module is called, so it's independent of PUT/DELETE/POST/GET sub-calls and now delivered with every call as `$request` parameter

2021-11-28 14:05 UTC, nupplaphil commented
@annando - can you check https://github.com/friendica/friendica/pull/11044/commits/09fda072385c2e8d306d4daa9b616b7d44c27e81 and https://github.com/friendica/friendica/pull/11044/commits/19603e228a56fdf3f54d9c0b82acaa26ecfa972f ?

This solves #11023 , but I had to remove `'type' => 'photo' at both cases

2021-11-28 14:56 UTC, annando commented
@nupplaphil I'm away until the evening. I try to have a look at it then.

2021-11-28 21:00 UTC, annando commented
@nupplaphil does the `exit` now exits again? In the current version it just adds content to the output but doesn't halt the execution.

Concerning handling the items. Here they are created: https://github.com/friendica/friendica/blob/2021.12-rc/mod/photos.php#L372-L391 So you could have a look at how to search for these posts.

2021-11-28 22:22 UTC, nupplaphil commented
> Why have you removed the `type` field?
> 
> Edit: I just realized that the field doesn't exists anymore. But you could check for the `post-type` set to `Item::PT_IMAGE` and `origin` set to `true`.

I'll change it, that was the missing hint, thx

2021-11-28 22:28 UTC, nupplaphil commented
> @nupplaphil does the `exit` now exits again? In the current version it just adds content to the output but doesn't halt the execution.

Aaahh I see. No the exit doesnt exit :D .. I'll rename the method. Concerning exiting => the exiting is triggered by the Module execution itself and not more by any subclass. In the end, every module execution returns a `ResponseInterface` with all necessary informationa to just print the response. So there's no more native `exit` calls during execution, just an output with different types :)

2021-11-29 00:09 UTC, MrPetovan commented
From #11023, throwing an `HTTPException` in an API module results in HTML errors being sent back in the response. I'd like us to find a way to guess the intended response format (HTML, JSON or XML) in a central place so that the Exception handler module can return the expected content type.

2021-11-29 03:09 UTC, MrPetovan requested changes

2021-11-29 03:09 UTC, MrPetovan commented on src/Module/Api/Friendica/Photo/Delete.php
> +	protected function post(array $request = [])
This endpoint still needs to accept DELETE requests.

2021-11-29 04:32 UTC, annando commented
@nupplaphil when you rename the `exit` then please also change the code at the places where it is called since there are occurrences where the program execution needs to stop.

2021-11-29 11:54 UTC, nupplaphil commented
> @nupplaphil when you rename the `exit` then please also change the code at the places where it is called since there are occurrences where the program execution needs to stop.
> 

Already done :)

2021-11-29 12:03 UTC, MrPetovan commented
Please merge #11037 first and rebase this larger PR on top of it, please note I had to fiddle with the `BaseModule->run` calls in the tests to skip the redundant `$post` parameter.

2021-11-30 05:47 UTC, MrPetovan commented
I went ahead and rebased this PR, pruning the commits I cherry-picked in #11037 and updating the tests with the changes to `BaseModule->run` parameters.

2021-11-30 06:13 UTC, MrPetovan approved these changes

2021-11-30 06:13 UTC, merged

2021-11-30 06:26 UTC, nupplaphil commented
> I went ahead and rebased this PR, pruning the commits I cherry-picked in #11037 and updating the tests with the changes to `BaseModule->run` parameters.

Thx! :)

2021-11-30 06:26 UTC, nupplaphil commented
> I went ahead and rebased this PR, pruning the commits I cherry-picked in #11037 and updating the tests with the changes to `BaseModule->run` parameters.

Thx! :)

2021-11-30 06:47 UTC, MrPetovan commented
As a general rule, I have more available time more frequently than you seem to do, so don't hesitate to open stub PRs with instructions for how to complete it, especially if it's about sweeping changes, and I can pick them up so we don't have to wait for your next availability.