Transform legacy API tests into new structure
friendica/friendica pull request #11127
Opened 2021-12-30 21:45 UTC by nupplaphil

uff ..

As the title says :-)

Things to say:
- I fixed a bug in the Twitter Destroy API: https://github.com/friendica/friendica/commit/0c4c6faa54cde9ff4067beaf7cdd14aeec987332
- The RSS API response always returns this array as response: https://github.com/friendica/friendica/blob/fb1e8e75f5eef9c4e05bec047bda6077e6c275de/src/Module/Api/ApiResponse.php#L102 (because of https://github.com/friendica/friendica/blob/fb1e8e75f5eef9c4e05bec047bda6077e6c275de/src/Module/Api/ApiResponse.php#L51 ) --> is this intended ? I guess not and maybe it's a bug I introduced :-/
- The failed test is intended because the legacy API tests assert that the text of a Twitter status starts with the title of a post - this behavior changed with the refactoring to the new structure (=> intended ?)

2022-01-01 20:42 UTC, nupplaphil commented
@annando / @MrPetovan - should the "text" and the "friendica_html" of the Twitter status object include the title or not? Before the refactoring, the tests assert it is included (and the field "friendica_html" was the former "html" field).

2022-01-01 21:34 UTC, annando commented
I simplified some functionality during the conversion into the new structure to reduce complexity. So I suggest that we define the current return values as expected.

2022-01-01 23:03 UTC, MrPetovan requested changes
Thank you for your work, although I'm not terribly happy with the several intermediate variables used only once in tests.

Instead of something like 
```php
$directMessageFactory = new DirectMessage(DI::logger(), DI::dba(), DI::twitterUser());
$directMessageObj     = $directMessageFactory->createFromMailId($id, ApiTest::SELF_USER['id']);
$directMessage        = $directMessageObj->toArray();
```
I'd much more prefer:
```php
$directMessage = (new DirectMessage(DI::logger(), DI::dba(), DI::twitterUser()))
	->createFromMailId($id, ApiTest::SELF_USER['id'])
	->toArray();
```
It is less verbose, achieve the same and you don't have to shorten `Factory` or `Object` ever again.

2022-01-01 23:03 UTC, MrPetovan commented on src/Factory/Api/Twitter/Status.php
> +		}
In `$title . $item['raw-body'] ?? $item['body']`, `$item['body']` will never be used because `$title` is defined the line before and the concatenation operator is evaluated before the null-coalescing `??` operator. I assume you wanted something like `$title . ($item['raw-body'] ?? $item['body'])` instead.

But then there's a simpler way to write all this:
```suggestion
		$title = '';
		$text = '';

		// Add the title to text / html if set
		if (!empty($item['title'])) {
			$text = $item['title'] . ' ';
			$title = sprintf("[h4]%s[/h4]\n", $item['title']);
		}

		$statusnetHtml = BBCode::convertForUriId($item['uri-id'], BBCode::setMentionsToNicknames($title . ($item['raw-body'] ?? $item['body'])), BBCode::API);
		$friendicaHtml = BBCode::convertForUriId($item['uri-id'], $title . $item['body'], BBCode::EXTERNAL);
```

2022-01-01 23:03 UTC, MrPetovan commented on tests/src/Factory/Api/Twitter/ActvitiesTest.php
> +class ActvitiesTest extends FixtureTest
Typo in class/file names:
```suggestion
class ActivitiesTest extends FixtureTest
```

2022-01-02 00:06 UTC, MrPetovan approved these changes
Looks much better, thanks!

2022-01-02 00:06 UTC, merged