Add native language names to language selector
friendica/friendica pull request #11141
Opened 2022-01-04 23:46 UTC by urbalazs

This is an idea how to improve the language selector fields. Now the drop-down fields contain native language names instead of language codes.

I tested this only in Profile -> Settings -> Account Settings -> Basic Settings and it works fine. However, this function is used in other parts of the framework. Please make sure before merging that this patch will not break anything.

2022-01-06 12:42 UTC, nupplaphil requested changes
As you said - this method is used at several places:
```
Method
    getAvailableLanguages
Usages in All Places  (6 usages found)
    Method call  (6 usages found)
        friendica  (6 usages found)
              (2 usages found)
                update.php  (2 usages found)
                    update_1298  (1 usage found)
                        67 $allLangs = DI::l10n()->getAvailableLanguages();
                    update_1441  (1 usage found)
                        1036 $languages = DI::l10n()->getAvailableLanguages();
            mod  (1 usage found)
                settings.php  (1 usage found)
                    settings_content  (1 usage found)
                        729 $lang_choices = DI::l10n()->getAvailableLanguages();
            src/Model  (1 usage found)
                Item.php  (1 usage found)
                    Item  (1 usage found)
                        getLanguage  (1 usage found)
                            1656 $availableLanguages = DI::l10n()->getAvailableLanguages();
            src/Module  (1 usage found)
                Install.php  (1 usage found)
                    Install  (1 usage found)
                        content  (1 usage found)
                            300 $lang_choices = $this->l10n->getAvailableLanguages();
            src/Module/Admin  (1 usage found)
                Site.php  (1 usage found)
                    Site  (1 usage found)
                        content  (1 usage found)
                            392 $lang_choices = DI::l10n()->getAvailableLanguages();
```

Can you check if the at least the Install workflow is still working as expected when changing the return structure? And just to be sure please check the Admin Site settings page as well

2022-01-23 19:09 UTC, nupplaphil approved these changes

2022-01-23 19:10 UTC, nupplaphil commented
@MrPetovan / @annando - Please double check this PR because I found a bug as well, which I fixed within this PR.
@urbalazs - I tested your PR and it worked fine, thank you for your contribution

2022-01-23 19:51 UTC, MrPetovan approved these changes
Looks good to me.

2022-01-23 19:55 UTC, merged