Added handling of some previously unhandled activities
friendica/friendica pull request #11385
Opened 2022-04-01 11:21 UTC by annando

Based on the received activity data, this PR adds the handling for some previously unhandled activities. Also unhandled activities can now be stored as files to improve a handling in the future.

2022-04-02 20:01 UTC, MrPetovan requested changes

2022-04-02 20:01 UTC, MrPetovan commented on src/Protocol/ActivityPub/Receiver.php
> +	 * Stores unhandled or unknown Activitities as a file
```suggestion
	 * Stores unhandled or unknown Activities as a file
```

2022-04-02 21:04 UTC, annando commented on src/Protocol/ActivityPub/Receiver.php
> +	 * Stores unhandled or unknown Activitities as a file
Just a little bit too much tities here ...

2022-04-04 14:59 UTC, MrPetovan approved these changes

2022-04-04 14:59 UTC, merged