Cache contact avatars locally as files
friendica/friendica pull request #11477
Opened 2022-05-08 05:46 UTC by annando

Currently we have got two ways accessing avatar pictures from remotes contacts. Either we store them in the database or we don't store them at all and just relay the access.

Not storing rhe saves a lot of database space. But the relaying doesn't seem to work reliably. Users often report that they see the default avatars.

To fix this problem a third way is introduced: We can now store the avatar pictures as files. Later they will be accessed directly via the web server, which reduces the overhead a lot.

This feature is meant as a fix but is still considered "experimental". In later versions this should be replaced with some option where admins can decide how to cache the avatars.

2022-05-08 06:55 UTC, nupplaphil commented
I would prefer that we extract these new functionality (Avatar Caching) in a new class and using the existing storage class methodology for it.

2022-05-08 07:24 UTC, annando commented
This feature is based upon the direct file access. Means: When avatars are stored this way then fetching them is completely done via the web server without any PHP call, any database access, whatsoever. This means that we cannot simply use the existing storage mechanism.

However, I can imagine that especially in a cluster environment it will make sense to deliver this static content via some dedicated machines or even via some CDN. This of course would mean some more changes and some new classes and so on. We cannot integrate it in the existing storage functionality for another reason: We cannot handle access permissions this way. So we will have to develop some completely new stuff.

But: This here is meant as a quick solution to reduce the load on larger systems. (I'm still not totally satisfied with the situation of one of my servers) It is currently implemented so that it won't interfere with the existing functionality (important for the RC phase) and that it delivers a quick relieve (important for my server).

2022-05-09 13:40 UTC, MrPetovan requested changes

2022-05-09 13:40 UTC, MrPetovan commented on src/Contact/Avatar.php
> +			Logger::notice('Avatar cache file could not be stored', ['file' => $filepath]);
Shouldn't be this a warning?

2022-05-09 14:30 UTC, annando commented on src/Contact/Avatar.php
> +			Logger::notice('Avatar cache file could not be stored', ['file' => $filepath]);
Yeah, I guess a warning would be okay as well. I was torn between those two levels. it is nasty when you cannot write that file, but it doesn't cause any immediate harm to the system.

2022-05-09 15:12 UTC, MrPetovan commented on src/Contact/Avatar.php
> +			Logger::notice('Avatar cache file could not be stored', ['file' => $filepath]);
Then warning is appropriate. It isn't critical, but it is something to fix.

2022-05-09 15:13 UTC, MrPetovan approved these changes

2022-05-09 15:13 UTC, merged