Respect Forwarded-For headers
friendica/friendica pull request #11680
Opened 2022-06-23 20:43 UTC by nupplaphil

We do now respect reverse proxies when retrieving IPs for different situations:

- Logging
- Cookies & Sessions

2022-06-23 20:56 UTC, MrPetovan requested changes

2022-06-23 20:56 UTC, MrPetovan commented on src/App/Request.php
> +	 * @param array               $server
```suggestion
	 * @param array               $server The $_SERVER array
```

2022-06-23 20:56 UTC, MrPetovan commented on src/App/Request.php
> +	const ORDERED_FORWARD_FOR_HEADER = 'HTTP_X_FORWARDED_FOR';
```suggestion
	/** @var string the default header that could contain the actual client IP in a proxy request */
	const DEFAULT_FORWARD_FOR_HEADER = 'HTTP_X_FORWARDED_FOR';
```

2022-06-23 21:01 UTC, nupplaphil commented on src/App/Request.php
> +	const ORDERED_FORWARD_FOR_HEADER = 'HTTP_X_FORWARDED_FOR';
This could be a list as well, I added some (hopefully) better documentation about it :)

2022-06-23 21:11 UTC, MrPetovan commented on src/App/Request.php
> +	 * Beware: This list is ordered
This comment belongs in the description of the `proxy.forwarded_for_headers` config value. It's unwarranted here since we control the value.

2022-06-23 21:11 UTC, MrPetovan commented on src/App/Request.php
> +	const ORDERED_FORWARD_FOR_HEADER = 'HTTP_X_FORWARDED_FOR';
But it's a constant and it isn't a list, so what's the point? I agree the description is warranted for the config value, but you already did it.

2022-06-23 21:12 UTC, MrPetovan requested changes

2022-06-23 21:12 UTC, MrPetovan commented on static/defaults.config.php
> +		// A comma separated list of all allowed header values to retrieve the real client IP
Please add that the headers are evaluated in order.

2022-06-24 14:12 UTC, MrPetovan approved these changes

2022-06-24 14:12 UTC, merged