Smarty: Configuration added to store without sub directories
friendica/friendica pull request #11895
Opened 2022-09-08 05:17 UTC by annando

Storing the template cache into several sub directories is supposed to increase the performance. However this can cause permission issues when the system uses different users for front end and worker. With this configuration we can restore the old behaviour.

2022-09-08 05:45 UTC, nupplaphil requested changes

2022-09-08 05:45 UTC, nupplaphil commented on src/Render/FriendicaSmarty.php
> +		$this->setUseSubDirs(DI::config()->get('smarty3', 'use_sub_dirs'));
Please add a new parameter `bool $useSubDirs` at the constructor and pass it through the call of it

2022-09-08 06:46 UTC, nupplaphil requested changes
You have to map the parameter into a private property of the class so you can use it inside. I added the missing lines, but I don't have tabs on my mobile phone keyboard (or at least I don't know how to add it)

2022-09-08 06:46 UTC, nupplaphil commented on src/Render/FriendicaSmarty.php
```suggestion
   private $useSubDirs;
```

2022-09-08 06:46 UTC, nupplaphil commented on src/Render/FriendicaSmarty.php
```suggestion
 $this->useSubDirs = $useSubDirs;
```

2022-09-08 06:46 UTC, nupplaphil commented on src/Render/FriendicaSmarty.php
> +		$this->setUseSubDirs($use_sub_dirs);
```suggestion
		$this->setUseSubDirs($this->useSubDirs);
```

2022-09-08 10:46 UTC, annando commented
@nupplaphil what is the advantage of doing so? we don't need that value inside the class.

2022-09-09 00:42 UTC, MrPetovan commented
There's no advantage of having it as a property if it's only used in the constructor, but it's better to have it as a constructor parameter than to use a static config call.

2022-09-09 06:20 UTC, merged

2022-09-09 06:21 UTC, nupplaphil commented
Uups.. sorry I oversaw in the Diff of GitHub that's in the same method .... Merged without any further comments :X