Fix /api/v1/push/subscription
friendica/friendica pull request #11933
Opened 2022-09-25 19:15 UTC by nupplaphil

Fixing #11722

2022-09-25 21:01 UTC, Quix0r requested changes
Otherwise looking fine.

2022-09-25 21:01 UTC, Quix0r commented on tests/src/Module/Api/Mastodon/PushSubscriptionTest.php
> +	public function testApiAccountVerifyCredentials()
You already added `: void` in `PushSubscription` class, can you please add it here?

2022-09-25 21:01 UTC, Quix0r commented on tests/src/Module/Api/Mastodon/PushSubscriptionTest.php
> +	public function testApiAccountVerifyCredentialsWithoutAuthenticatedUser()
You already added `: void` in `PushSubscription` class, can you please add it here?

2022-09-25 21:44 UTC, Quix0r approved these changes

2022-09-26 01:12 UTC, MrPetovan requested changes

2022-09-26 01:12 UTC, MrPetovan commented on src/Module/Api/Mastodon/PushSubscription.php
> +			'uid'    => $uid, 'fields' => $fields
If you're going for readability, please use the full length declaration. In this context, please add a trailing comma on each line to streamline diffs.
```suggestion
			'result'         => $ret,
			'application-id' => $application['id'],
			'uid'            => $uid,
			'fields'         => $fields,
```

2022-09-26 01:12 UTC, MrPetovan commented on src/Module/Api/Mastodon/PushSubscription.php
> +			'uid'    => $uid
```suggestion
			'result'         => $ret,
			'application-id' => $application['id'],
			'uid'            => $uid,
```

2022-09-26 08:56 UTC, Quix0r approved these changes

2022-09-26 11:32 UTC, MrPetovan approved these changes

2022-09-26 11:32 UTC, merged