Moved GRAVITY_* constants to Item model class
friendica/friendica pull request #11997
Opened 2022-10-14 22:54 UTC by Quix0r

According to @MrPetovan constants in `boot.php` that are not used in configuration files can be safely moved to proper classes. This PR moves all `GRAVITY_*` constants to `Friendica\Model\Item` class.

2022-10-15 13:09 UTC, MrPetovan requested changes

2022-10-15 13:09 UTC, MrPetovan commented on mod/oexchange.php
> +	$s = BBCode::embedURL($url, true, $title, $description, $tags);
The related `use Friendica\Content\Text\BBCode;` statement seems to be missing.

2022-10-15 13:09 UTC, MrPetovan commented on mod/oexchange.php
> -	$post['body'] = Friendica\Content\Text\HTML::toBBCode($s);
The related `use Friendica\Content\Text\HTML;` statement seems to be missing.

2022-10-15 13:09 UTC, MrPetovan commented on mod/tagger.php
> +		'body'          => sprintf( $bodyverb, $ulink, $alink, $plink, $termlink),
Code standards.
```suggestion
		'body'          => sprintf($bodyverb, $ulink, $alink, $plink, $termlink),
```

2022-10-15 13:09 UTC, MrPetovan commented on view/theme/frio/theme.php
>  use Friendica\Model;
Is this still needed?

2022-10-15 13:16 UTC, annando commented
Overall the usage of an IDE with built-in syntax checker would help here. Especially with this huge amount of files, the possibility of syntax errors is immense.

It would be much better, not to have performed multiple steps (exchanging the constants and code reformatting) in one huge PR. Also it would had been better to keep the old constants for some time and just deprecating them, since they are also used in the addons.

2022-10-18 14:29 UTC, Quix0r commented on view/theme/frio/theme.php
>  use Friendica\Model;
I don't know. But that the fact that themes can have access to database (circumventing the controller) is scary.

2022-10-18 14:31 UTC, Quix0r commented
> Overall the usage of an IDE with built-in syntax checker would help here. Especially with this huge amount of files, the possibility of syntax errors is immense.
I strongly disagree here. Better more unit-testing which would "on-the-fly" test this for us as a by-product.

2022-10-18 14:40 UTC, Quix0r commented
And for addons, I have also made a branch ready for PR.

2022-10-18 15:25 UTC, MrPetovan approved these changes

2022-10-18 15:31 UTC, merged