Improved handling of native quotes
friendica/friendica pull request #12076
Opened 2022-10-29 22:17 UTC by annando

We are now only storing non native quotes in the body. All native quotes are done via the quote-uri-id field in the post. The whole code is cleaned up around this.

This PR has to be merged at the same time as the addon PR.

2022-10-29 22:37 UTC, MrPetovan requested changes

2022-10-29 22:37 UTC, MrPetovan commented on src/Content/Item.php
> +		$body .= "\n♲ " . $link;
Energy is expensive, let's save the creation of an intermediary variable.
```suggestion
		$body .= "\n♲ " . ($post['plink'] ?: $post['uri']);
```

2022-10-29 22:37 UTC, MrPetovan commented on src/Model/Item.php
> +		return $shared_item['uri-id'];
I'd rather we used early returns than the repetitive `empty($shared_item['uri-id'])` condition which means something different every time.
```suggestion
		if (!empty($shared['guid'])) {
			$shared_item = Post::selectFirst(['uri-id'], ['guid' => $shared['guid'], 'uid' => [0, $uid]]);
			if (!empty($shared_item['uri-id'])) {
				Logger::debug('Found post by guid', ['guid' => $shared['guid'], 'uid' => $uid]);
				return $shared_item['uri-id'];
			}
		}

		if (!empty($shared['message_id'])) {
			$shared_item = Post::selectFirst(['uri-id'], ['uri' => $shared['message_id'], 'uid' => [0, $uid]]);
			if (!empty($shared_item['uri-id'])) {
				Logger::debug('Found post by message_id', ['message_id' => $shared['message_id'], 'uid' => $uid]);
				return $shared_item['uri-id'];
			}
		}

		if (!empty($shared['link'])) {
			$shared_item = Post::selectFirst(['uri-id'], ['plink' => $shared['link'], 'uid' => [0, $uid]]);
			if (!empty($shared_item['uri-id'])) {
				Logger::debug('Found post by link', ['link' => $shared['link'], 'uid' => $uid]);
				return $shared_item['uri-id'];
			}
		}

		$url = $shared['message_id'] ?: $shared['link'];
		$id = self::fetchByLink($url);
		if (!$id) {
			Logger::notice('Post could not be fetched.', ['url' => $url, 'uid' => $uid]);
			return 0;
		}

		Logger::debug('Fetched shared post', ['id' => $id, 'url' => $url, 'uid' => $uid]);

		$shared_item = Post::selectFirst(['uri-id'], ['id' => $id]);
		if (!DBA::isResult($shared_item)) {
			Logger::warning('Post does not exist.', ['id' => $id, 'url' => $url, 'uid' => $uid]);
			return 0;
		}

		return $shared_item['uri-id'];
```

2022-10-29 23:10 UTC, annando commented
@MrPetovan changes are applied.

2022-10-29 23:29 UTC, MrPetovan requested changes

2022-10-29 23:29 UTC, MrPetovan commented on src/Model/Item.php
> +		return $shared_item['uri-id'];
Almost there, no need for an `else` statement here and we can avoid a negative condition.
```suggestion
		if (DBA::isResult($shared_item)) {
			Logger::debug('Fetched shared post', ['id' => $id, 'url' => $url, 'uid' => $uid]);
			return $shared_item['uri-id'];
		}

		Logger::warning('Post does not exist.', ['id' => $id, 'url' => $url, 'uid' => $uid]);
		return 0;
```

2022-10-29 23:33 UTC, MrPetovan commented
Does this fix #12073 ?

2022-10-29 23:52 UTC, annando commented
Yeah

2022-10-30 01:29 UTC, MrPetovan commented
Did you see my second Change Request?

2022-10-30 12:43 UTC, MrPetovan approved these changes

2022-10-30 12:43 UTC, merged