Public calendar
friendica/friendica pull request #12227
Opened 2022-11-20 22:30 UTC by matthiasmoritz

This Feature allows users to provid the own Calendar to all (and even anonymus) visitors.

It's my first pice of code for friendica, and my first pull request to a open source project so code quality might be not perfect ;)

2022-11-20 22:37 UTC, matthiasmoritz commented
By the way, is there any tutorial how to execute the checks?

2022-11-20 22:54 UTC, nupplaphil requested changes

2022-11-20 22:54 UTC, nupplaphil commented on src/Model/Event.php
> +		 */
Please move this part to a PHP Doc header

2022-11-20 22:54 UTC, nupplaphil commented on src/Model/Event.php
> +		$events = self::getById( $event_id, '' );
```suggestion
		$events = self::getById($event_id, '');
```

2022-11-20 22:54 UTC, nupplaphil commented on src/Model/Event.php
> +	private static function getById ( int $event_id, string $additionalCondition) : array
```suggestion
	private static function getById (int $event_id, string $additionalCondition) : array
```

2022-11-20 22:54 UTC, nupplaphil commented on src/Module/Calendar/Event/Get.php
> +			System::jsonExit($events ? self::map($events) : []);
```suggestion
		if (!$this->session->getLocalUserId() && !Feature::isEnabled($calenderOwner['uid'] ?? $this->session->getLocalUserId(), 'public_calendar')) {
			throw new HTTPException\UnauthorizedException();
		}

		// get events by id or by date
		if (!empty($request['id']) && !Feature::isEnabled($calenderOwner['uid'] ?? $this->session->getLocalUserId(), 'public_calendar')) {
			$events = [Event::getByIdAndUid($this->session->getLocalUserId(), $request['id'], $this->parameters['nickname'] ?? null)];
		} elseif (!empty($request['id']) && Feature::isEnabled($calenderOwner['uid'] ?? $this->session->getLocalUserId(), 'public_calendar')) {
			$events = [Event::getPublicById($request['id'])];
		} else {
			$events = Event::getListByDate($this->session->getLocalUserId(), $request['start'] ?? '', $request['end'] ?? '', false, $this->parameters['nickname'] ?? null);
		}

		System::jsonExit($events ? self::map($events) : []);
```

2022-11-20 22:54 UTC, nupplaphil commented on src/Module/Calendar/Event/Get.php
> +		//if (Feature::isEnabled($calenderOwner['uid'] ?? $this->session->getLocalUserId(), 'public_calendar') && !empty($request['id']) ){
Can you delete this if it isn't necessary anymore?

2022-11-20 22:56 UTC, MrPetovan commented
The checks are meant to be run by GitHub when you submit a PR and any time you push the branch. If you want to perform these checks in advance of the review, you can open a Draft PR (or convert this one to Draft) so that there's no pressure to add more changes to it.

2022-11-20 22:56 UTC, nupplaphil commented
Thank you for your help!! :)

Additionally, can you:
- Rebase this branch onto the latest `develop`. This will fix some checks
- Recreate the `view/lang/C/messages.po` --> plz execute the `bin/run_xgettext.sh` script to do that

2022-11-21 03:16 UTC, MrPetovan commented
Thank you for your work! For consistency, Friendica currently enforces the PSR-2 coding standards, see https://www.php-fig.org/psr/psr-2/

I've noticed too many violations in your changes to individually point them out, would like to take a first pass or for me to take over the branch?

2022-11-21 08:46 UTC, matthiasmoritz commented
@MrPetovan let me first go through the code. There is also still one functional issue that can cause privacy errors. I'll update the PR.

2022-11-22 20:34 UTC, matthiasmoritz commented
@MrPetovan can you please take over the PR. The Feature is working as excepted but I'm not shure how to continiue with the rest.

2022-11-22 23:18 UTC, MrPetovan commented
I will, thank you for your work!

2022-11-23 00:23 UTC, MrPetovan commented
Oh Lord, I'm diving down the calendar rabbit hole and nothing about the whole feature seems to make sense (not your specific changes) and I'm rewriting way more than I should but this is the life that chose me.

2022-11-23 05:35 UTC, matthiasmoritz commented
Sorry for opening pandoras box 😬

2022-11-23 05:59 UTC, Quix0r approved these changes
Type-hint checks are fine so far.

2022-11-30 23:17 UTC, MrPetovan commented
Alright! This took me on two separate tangents (the theme variables and the `hidewall` setting) before getting to the main issue which is event retrieval and permission check, but it's there.

@matthiasmoritz You may be surprised to find very little of your own changes in the final PR, this is because I've simplified the existing `Model\Event` methods, which made many of your changes unnecessary.

Overall, there was a lot of unused/confusing code I removed and it's always a good thing.

The `hidewall` setting has been normalized (it was inconsistent in checking for authentication) and now covers a few more endpoints, including syndication feeds, so I've edited the setting description to reflect this new state of affairs, hopefully it's clearer.

2022-12-01 12:54 UTC, Quix0r approved these changes
Type-hint check okay.

2022-12-01 16:27 UTC, merged

2022-12-01 16:27 UTC, nupplaphil commented
Here we go :-) LGTM

2022-12-01 16:42 UTC, MrPetovan commented
@matthiasmoritz Thank you for your work again! You've helped improve Friendica on three separate fronts!

2022-12-01 19:17 UTC, matthiasmoritz commented
Not so sure how my three lines of code contributed to your work :) but anyway, I can test the feature and i think you broke something in the UI. See #12308
![image](https://user-images.githubusercontent.com/1984982/205140286-f51593ef-f69b-4868-806f-db910de7fd7c.png)

2022-12-01 19:57 UTC, MrPetovan commented
Are you sure it was working before? Do you want to look into it? This display comes from the `Module\Event\Show` class.

I've noticed we were performing a `Strings::escapeHTML` before a `BBCode::convert` so this may be the result of a double-encoding issue.

2022-12-01 20:46 UTC, matthiasmoritz commented
It works on stable 🤷‍♂️

2022-12-01 21:52 UTC, MrPetovan commented
So it could be a regression. I'll look into it if you don't want to.