Code cleanup for mod/item.php
friendica/friendica pull request #12609
Opened 2023-01-04 05:51 UTC by annando

This is some kind of intermediate PR. This is a preparation to make mod/item.php being able to be moved to some Module class.

2023-01-04 20:18 UTC, MrPetovan approved these changes

2023-01-04 22:10 UTC, nupplaphil commented
The phpunit is currently stuck because my server crashed during an RAM upgrade with all Friendica and CI instances on it ;-) .. *gg*

2023-01-04 22:13 UTC, MrPetovan approved these changes

2023-01-07 18:39 UTC, MrPetovan requested changes

2023-01-07 18:39 UTC, MrPetovan commented on mod/item.php
> +	if (!DI::userSession()->isAuthenticated() || !$uid) {
You only need the $uid part as the “isAuthenticated” method will alway be true if the $uid is set.
```suggestion
	if (!$uid) {
```

2023-01-07 18:39 UTC, MrPetovan commented on mod/item.php
> +		DI::sysmsg()->addNotice(DI::l10n()->t('Unable to locate original post.'));
This is superfluous if we throw an Exception. Please move this inside the $return_path block.

2023-01-07 18:39 UTC, MrPetovan commented on mod/item.php
> +		if ($post['parent']) {
Duplicate condition, you can remove it.

2023-01-07 18:39 UTC, MrPetovan commented on mod/item.php
>  		if (DBA::isResult($parent_item)) {
DBA::isResult is superfluous with “selectFirst”
```suggestion
		if ($parent_item) {
```

2023-01-07 18:39 UTC, MrPetovan commented on mod/item.php
> +	if (!DBA::isResult($post)) {
Same here
```suggestion
	if (!$post) {
```

2023-01-07 18:39 UTC, MrPetovan commented on mod/item.php
> +		DI::sysmsg()->addNotice(DI::l10n()->t('Empty post discarded.'));
Please move this inside the return_path block

2023-01-07 18:39 UTC, MrPetovan commented on src/Content/Item.php
> +		if (!DBA::isResult($user)) {
```suggestion
		if (!$user) {
```

2023-01-07 18:39 UTC, MrPetovan commented on src/Content/Item.php
> +		if (strlen($post['allow_gid']) || strlen($post['allow_cid']) || strlen($post['deny_gid']) || strlen($post['deny_cid'])) {
Superfluous function calls.
```suggestion
		if ($post['allow_gid'] || $post['allow_cid'] || $post['deny_gid'] || $post['deny_cid']) {
```

2023-01-07 18:39 UTC, MrPetovan commented on src/Content/Item.php
> +			if (strlen($post['attach'])) {
```suggestion
			if ($post['attach']) {
```

2023-01-07 18:39 UTC, MrPetovan commented on src/Content/Item.php
> +			if (!strlen($address)) {
```suggestion
			if (!$address) {
```

2023-01-07 18:44 UTC, annando commented on mod/item.php
> +	if (!DI::userSession()->isAuthenticated() || !$uid) {
Done

2023-01-07 18:47 UTC, annando commented on mod/item.php
> +		DI::sysmsg()->addNotice(DI::l10n()->t('Unable to locate original post.'));
Done

2023-01-07 18:49 UTC, annando commented on src/Content/Item.php
> +			if (!strlen($address)) {
Done

2023-01-07 19:02 UTC, MrPetovan approved these changes

2023-01-07 19:03 UTC, merged