First implementation of ActivityPub C2S
friendica/friendica pull request #12752
Opened 2023-01-29 15:06 UTC by annando

This PR adds a very basic and experimental support for "ActivityPub Client to Server", means the part between a client software and the system. The only client that I currently know of is AndStatus. And at least some data is visible, although the system behaves weird, see https://github.com/andstatus/andstatus/issues/573

Posting is currently not supported and it is far from "Production Status".

2023-01-29 16:41 UTC, MrPetovan requested changes

2023-01-29 16:41 UTC, MrPetovan commented on src/Module/ActivityPub/Whoami.php
> + * Dummy class for all currently unimplemented endpoints
Is this accurate?

2023-01-29 16:41 UTC, MrPetovan commented on src/Object/Api/Mastodon/Token.php
> +	 * @param string $me
Please explicit the expected format of this parameter (a profile URL?).

2023-01-29 17:48 UTC, annando commented on src/Module/ActivityPub/Whoami.php
> + * Dummy class for all currently unimplemented endpoints
Mostly. :grin:

2023-01-29 18:12 UTC, annando commented on src/Module/ActivityPub/Whoami.php
> + * Dummy class for all currently unimplemented endpoints
Done

2023-01-31 10:34 UTC, MrPetovan commented on src/Object/Api/Mastodon/Token.php
> +	 * @param string $me
Please add parameter documentation so that I can merge this PR.

2023-02-01 16:48 UTC, MrPetovan approved these changes

2023-02-01 16:48 UTC, merged