Fix multiple serialized values
friendica/friendica pull request #12814
Opened 2023-02-19 11:58 UTC by nupplaphil

Closes #12803

2023-02-19 13:07 UTC, Quix0r approved these changes
Looking fine to me.

2023-02-19 17:26 UTC, MrPetovan requested changes
Language

2023-02-19 17:26 UTC, MrPetovan commented on src/Core/Config/Util/SerializeUtil.php
> +	 * @param mixed $value A possible serialized value
```suggestion
	 * @param mixed $value A possibly serialized value
```

2023-02-19 23:52 UTC, MrPetovan approved these changes

2023-02-20 13:13 UTC, Quix0r approved these changes

2023-02-20 13:28 UTC, MrPetovan requested changes
Database version has increased since your changes, please rebase your branch.

2023-02-20 16:54 UTC, MrPetovan approved these changes

2023-02-20 16:54 UTC, merged