Mastodon edit title spoiler update
friendica/friendica pull request #12878
Opened 2023-03-11 14:29 UTC by HankG

The handling of the spoiler text/title editing in Mastodon API was inconsistent with the creation endpoint. This change aligns the two.

2023-03-11 20:36 UTC, MrPetovan approved these changes

2023-03-11 20:55 UTC, annando commented
Yeah, I hadn't got time by now, testing which changes I have to apply when I remove that `toArray` call.

2023-03-12 06:50 UTC, MrPetovan requested changes

2023-03-12 06:50 UTC, MrPetovan commented on src/Module/Api/Mastodon/Statuses.php
> +		if ($post['gravity'] == 0) {
Please use the corresponding constant reference instead of the static value:
```suggestion
		if ($post['gravity'] == Item::GRAVITY_PARENT) {
```

2023-03-12 06:50 UTC, MrPetovan commented on src/Module/Api/Mastodon/Statuses.php
> +			if (!isset($request['friendica']['title']) && $post['gravity'] == 0 && DI::pConfig()->get($uid, 'system', 'api_spoiler_title', true)) {
```suggestion
			if (!isset($request['friendica']['title']) && $post['gravity'] == Item::GRAVITY_PARENT && DI::pConfig()->get($uid, 'system', 'api_spoiler_title', true)) {
```

2023-03-12 18:39 UTC, MrPetovan approved these changes

2023-03-12 18:39 UTC, merged