Remove tabs if followed by new lines (or vice versa)
friendica/friendica pull request #12917
Opened 2023-03-19 20:22 UTC by annando

Sometimes there can be tabs in the BBCode. We can safely remove them when new lines are around. Same goes with line feeds.

2023-03-19 20:26 UTC, nupplaphil commented
New/adapting test? :-X .. :-)

2023-03-19 20:38 UTC, annando commented
Too late for today :sleeping_bed:

2023-03-19 23:22 UTC, MrPetovan commented
Nothing to do for tests until I remove the `system.remove_duplicated lines` config key next release. The changed code isn’t currently hit by the tests because of the default value for this key.

2023-03-19 23:42 UTC, MrPetovan requested changes

2023-03-19 23:42 UTC, MrPetovan commented on src/Content/Text/BBCode.php
> +						"\n\n\n", "\n ", " \n", "\n\t", "\t\n", "\n\r", "\r\n", "[/quote]\n\n", "\n[/quote]", "[/li]\n", "\n[li]", "\n[*]", "\n[ul]", "[/ul]\n", "\n\n[share ", "[/attachment]\n",
The CRLF conversion to LF is already done on line 1273.
```suggestion
						"\n\n\n", "\n ", " \n", "\n\t", "\t\n", "\n\r", "[/quote]\n\n", "\n[/quote]", "[/li]\n", "\n[li]", "\n[*]", "\n[ul]", "[/ul]\n", "\n\n[share ", "[/attachment]\n",
```

2023-03-19 23:42 UTC, MrPetovan commented on src/Content/Text/BBCode.php
> +						"\n\n", "\n", "\n", "\n", "\n", "\n", "\n", "[/quote]\n", "[/quote]", "[/li]", "[li]", "[*]", "[ul]", "[/ul]", "\n[share ", "[/attachment]",
```suggestion
						"\n\n", "\n", "\n", "\n", "\n", "\n", "[/quote]\n", "[/quote]", "[/li]", "[li]", "[*]", "[ul]", "[/ul]", "\n[share ", "[/attachment]",
```

2023-03-20 07:04 UTC, annando commented
Test is added

2023-03-20 11:09 UTC, MrPetovan approved these changes

2023-03-20 11:09 UTC, merged