Issue 12701: Fix Markdown problems with Quotes
friendica/friendica pull request #12920
Opened 2023-03-20 21:39 UTC by annando

Fixes #12701
The Diaspora Markdown parser has got a problem with quotes in the "title" field. So we don't transmit them in case they contain a quote sign. This is no accessibility problem, since we always transmit the "alt" description and it is parsed by Diaspora.

2023-03-20 21:45 UTC, nupplaphil commented
I'm sorry... I.. must.. say.. it...

Tests? :X .. :X :-)

2023-03-20 21:48 UTC, annando commented
Do we have got tests for `BBCode::toMarkdown`?

2023-03-20 21:52 UTC, nupplaphil commented
https://github.com/friendica/friendica/blob/2023.03-rc/tests/src/Content/Text/BBCodeTest.php#L336

2023-03-21 01:06 UTC, MrPetovan submitted a review, later dismissed

2023-03-21 01:06 UTC, MrPetovan commented on src/Content/Text/BBCode.php
> +						// Fix for Markdown problems wirh Diaspora, see issue #12701
```suggestion
						// Fix for Markdown problems with Diaspora, see issue #12701
```

2023-03-21 01:06 UTC, MrPetovan requested changes
Typo

2023-03-21 04:26 UTC, annando commented on src/Content/Text/BBCode.php
> +						// Fix for Markdown problems wirh Diaspora, see issue #12701
Fixed

2023-03-21 06:23 UTC, merged

2023-03-21 12:02 UTC, MrPetovan commented on tests/src/Content/Text/BBCodeTest.php
> +	public function testToMarkdown(string $expected, string $text, $for_diaspora = true)
This argument’s default value should match the tested method’s. To provide a different value for a test case, you need to mention it in the data array.

2023-03-21 12:02 UTC, MrPetovan commented on tests/src/Content/Text/BBCodeTest.php
> +			],
***suggestion
				'for_diaspora' => true,
			],
***

2023-03-21 12:02 UTC, MrPetovan commented on tests/src/Content/Text/BBCodeTest.php
> +			],
***
				'for_diaspora' => true,
			],
***

2023-03-21 16:02 UTC, annando commented on tests/src/Content/Text/BBCodeTest.php
> +	public function testToMarkdown(string $expected, string $text, $for_diaspora = true)
That's exactly what I did: https://github.com/friendica/friendica/blob/2023.03-rc/src/Content/Text/BBCode.php#L2036

2023-03-21 19:05 UTC, MrPetovan commented on tests/src/Content/Text/BBCodeTest.php
> +	public function testToMarkdown(string $expected, string $text, $for_diaspora = true)
Cool, I found the opposite when I updated the BBCode tests so I thought it was the same dynamic here. I’m on mobile all week so I can’t easily check.