Modify dropzones css to take it into account of themes fixes #12924
friendica/friendica pull request #12931
Opened 2023-03-22 10:05 UTC by xundeenergie

I modified the dropzone-css and the place where it will be loaded to make dropzone better configureable with color-schemes and css-variables.

It fixes https://github.com/friendica/friendica/issues/12924

2023-03-22 15:02 UTC, MrPetovan requested changes

2023-03-22 15:02 UTC, MrPetovan commented on view/theme/frio/css/dropzone.frio.css
The indentation changes to this file look wrong, only the first level was changed. Please have the indentation consistent through the file.

2023-03-22 15:02 UTC, MrPetovan commented on view/theme/frio/templates/head.tpl
> +<!--link rel="stylesheet" href="view/theme/frio/css/dropzone.frio.css?v={{$smarty.const.FRIENDICA_VERSION}}"
Please remove commented out code before creating a PR.

2023-03-22 15:21 UTC, xundeenergie commented on view/theme/frio/css/dropzone.frio.css
now it should be fixed.

How can i check this myself? 
My experiences with woodpecker are almost zero...

2023-03-22 15:22 UTC, xundeenergie commented
In the conflicting file, the "color: white;" must be removed!

2023-03-22 15:44 UTC, MrPetovan commented
To fix the conflict, rebase your branch on the latest 2023.03-rc, then edit the file to fix the conflict and continue the rebase as indicated in `git status`.

2023-03-22 18:47 UTC, MrPetovan commented
And now you need to do it again since I merged the same PR for the minified file. 😅

2023-03-22 20:43 UTC, xundeenergie commented
okeeeee :D

It's rebased again.

2023-03-23 00:42 UTC, MrPetovan approved these changes

2023-03-23 00:42 UTC, merged