Address a few Warning messages
friendica/friendica pull request #12953
Opened 2023-03-27 00:59 UTC by MrPetovan

- Address https://github.com/friendica/friendica/issues/12488#issuecomment-1445193699
- Address https://github.com/friendica/friendica/issues/12488#issuecomment-1445359764
- Address https://github.com/friendica/friendica/issues/12488#issuecomment-1448297639
- Address https://github.com/friendica/friendica/issues/12488#issuecomment-1483811015

2023-03-27 06:46 UTC, annando commented
Some of the warnings seem to be hints for other problems. We shouldn't suppress the warnings here, but should have a look at why this is happening.

2023-03-27 06:51 UTC, annando requested changes

2023-03-27 06:51 UTC, annando commented on src/Content/Item.php
> +			if ((isset($item['gravity']) && $item['gravity'] == ItemModel::GRAVITY_COMMENT) || empty($contact['cid']) || ($contact['contact-type'] != Contact::TYPE_COMMUNITY)) {
`Gravity` should be defined here. We shouldn't ignore this warning.

2023-03-27 06:51 UTC, annando commented on src/Model/Item.php
> +		if (isset($item['verb']) && $item['verb'] == Activity::FOLLOW) {
I guess that this happens because `verb` is missing in Statuses.php.

2023-03-27 10:06 UTC, nupplaphil commented
What about logging these warnings as "real" warnings with context instead? So we can investigate it further

2023-03-27 12:28 UTC, MrPetovan commented
Oh I know the cause for all of these, and I fixed them accordingly. There's no further investigation needed for these.

2023-03-27 12:29 UTC, MrPetovan commented
@annando 
> I guess that this happens because verb is missing in Statuses.php.

Indeed, same as with gravity, and I also assume the default value isn't `Activity::FOLLOW`.

(I can't seem to be able to answer on a review conversation thread, the Ajax calls returns 500 systematically.)

2023-03-31 18:15 UTC, MrPetovan commented
Superseded by https://github.com/friendica/friendica/pull/12963

2023-03-31 18:15 UTC, closed without merging