Store "audience" and "attributedTo" data
friendica/friendica pull request #13000
Opened 2023-04-14 17:30 UTC by annando

While analyzing the Lemmy issue with the missing pictures, I came across the "audience" field that we haven't handled before. We now store it and will see if we possibly use it at a later point in time. Also for debugging purposed we now store the "attributedTo" in a different place, since according to the specs this can be an array - although most implementations don't use an array for that. Possibly we will use the content in the field at a later point in time.

Since this isn't a bugfix, we possibly should postpone this PR to the next version.

2023-04-14 17:41 UTC, MrPetovan requested changes

2023-04-14 17:41 UTC, MrPetovan commented on src/Module/PermissionTooltip.php
> +				}
```suggestion
			}
```

2023-04-14 17:41 UTC, MrPetovan commented on src/Protocol/ActivityPub/ClientToServer.php
> +				}
```suggestion
			}
```

2023-04-14 17:41 UTC, MrPetovan commented on src/Protocol/ActivityPub/Receiver.php
> +						}
```suggestion
					}
```

2023-04-14 19:47 UTC, MrPetovan approved these changes

2023-04-14 19:48 UTC, MrPetovan commented
I've changed the merge base, you may have to rebase the branch on develop once it's brought to the new stable release.

2023-04-23 21:23 UTC, annando commented
@MrPetovan Conflicts are solved, the PR is now mergeable.

2023-04-23 23:40 UTC, MrPetovan approved these changes

2023-04-23 23:40 UTC, merged