The Emojipicker is added to Frio for new posts
friendica/friendica pull request #13084
Opened 2023-05-04 10:56 UTC by annando

It is now possible to add emojis via a dialogue in new post with the Frio theme. In upcoming PRs it should be added to Vier and comments.

2023-05-04 12:22 UTC, MrPetovan requested changes

2023-05-04 12:22 UTC, MrPetovan commented on view/templates/head.tpl
> +<link rel="stylesheet" href="view/js/button/frio.css?v={{$smarty.const.FRIENDICA_VERSION}}" type="text/css" media="screen" />
This file isn't part of this PR.

2023-05-04 15:24 UTC, annando commented on view/templates/head.tpl
> +<link rel="stylesheet" href="view/js/button/frio.css?v={{$smarty.const.FRIENDICA_VERSION}}" type="text/css" media="screen" />
Done

2023-05-04 15:30 UTC, MrPetovan approved these changes

2023-05-04 15:30 UTC, merged

2023-05-15 11:47 UTC, MrPetovan commented on view/theme/frio/templates/head.tpl
> +<link rel="stylesheet" href="view/js/button/frio.css?v={{$smarty.const.FRIENDICA_VERSION}}"
I missed this other reference to a non-existing file.