Added type-hints, reformatted arrays
friendica/friendica pull request #13208
Opened 2023-06-09 19:52 UTC by Quix0r

Changes:
- add type-hints
- replaced double-quotes with single
- changed a lot $array['foo'] into a single `$foo = ['foo' => $somethingFoo, 'bar' => $somethingBar];`

2023-06-09 20:14 UTC, MrPetovan requested changes

2023-06-09 20:14 UTC, MrPetovan commented on src/Network/Probe.php
> +	 * @todo Choice: implement $cache parameter or remove documentation
Please remove the obsolete parameter documentation.

2023-06-09 20:14 UTC, MrPetovan commented on src/Protocol/Diaspora.php
> +				throw new BadRequestException();
We already import `Friendica\Network\HTTPException`
```suggestion
				throw new HTTPException\BadRequestException();
```

2023-06-09 20:14 UTC, MrPetovan commented on src/Protocol/Diaspora.php
> +use Friendica\Network\HTTPException\BadRequestException;
We already import `Friendica\Network\HTTPException`
```suggestion
```

2023-06-09 20:14 UTC, MrPetovan commented on src/Protocol/Diaspora.php
> +					throw new BadRequestException();
We already import `Friendica\Network\HTTPException`
```suggestion
				throw new HTTPException\BadRequestException();
```

2023-06-09 20:14 UTC, MrPetovan commented on src/Protocol/Diaspora.php
> +				throw new BadRequestException();
We already import `Friendica\Network\HTTPException`
```suggestion
				throw new HTTPException\BadRequestException();
```

2023-06-09 20:14 UTC, MrPetovan commented on src/Protocol/Diaspora.php
> +				throw new BadRequestException();
We already import `Friendica\Network\HTTPException`
```suggestion
				throw new HTTPException\BadRequestException();
```

2023-06-09 20:14 UTC, MrPetovan commented on src/Protocol/Diaspora.php
> +				throw new BadRequestException();
We already import `Friendica\Network\HTTPException`
```suggestion
				throw new HTTPException\BadRequestException();
```

2023-06-09 20:14 UTC, MrPetovan commented on src/Protocol/Diaspora.php
>  			$datarray['object-type'] = Activity\ObjectType::NOTE;
Overriding the key with the same value.
```suggestion
```

2023-06-09 20:33 UTC, MrPetovan approved these changes

2023-06-09 20:33 UTC, merged

2023-06-26 12:17 UTC, annando commented
This PR causes the issue https://github.com/friendica/friendica/issues/13221 - this evening I will provide a fix.

2023-06-26 18:52 UTC, Quix0r commented
> This PR causes the issue #13221 - this evening I will provide a fix.

Ops, sorry that this happened.