Better support for "audience" / simplified Lemmy processing
friendica/friendica pull request #13226
Opened 2023-06-18 17:30 UTC by annando

This PR does contain a mixture of different tasks, since working on the central task took a long time. With these changes a lot of issues with Lemmy should be fixed now. Posts (and comments) to Lemmy will now be distributed only to the server, not the own followers.

To explain: Lemmy is using the "audience" field for signalling that it is a group post. We introduced that field for our own groups as well (this PR here also contains some improvements there as well). So we now have a close look on that field and process that in the best way.

Also this PR does contain some fixes that occur in between. For example Bluesky-URIs are no HTTP links, so clicking on the don't make sense. So we now automatically display a link to the contact "alias" if the URL is no HTTP link. Also some parts of the code are reformatted as well.

2023-06-18 19:18 UTC, MrPetovan requested changes
Next time, please submit your formatting changes separately.

2023-06-18 19:18 UTC, MrPetovan commented on src/Content/Widget/VCard.php
> +			$url = $contact['url'];
Please rename the variable to `$contact_url` for better visibility.
```suggestion
			$contact_url = $contact['alias'];
		} else {
			$contact_url = $contact['url'];
```

2023-06-18 19:18 UTC, MrPetovan commented on src/Model/Item.php
> +	 * This does not apply to posts that are sent only in parallel to a group.
What does this mean? Are both behaviors (parallel and not-parallel?) described somewhere?

2023-06-18 19:18 UTC, MrPetovan commented on src/Module/Contact.php
> +				break;
Less legible change, please revert.

2023-06-18 19:18 UTC, MrPetovan commented on src/Module/Contact.php
> +				$header = DI::l10n()->t('Contacts');
Less legible change, please revert.

2023-06-18 19:18 UTC, MrPetovan commented on src/Module/Magic.php
>  		if ($addr ?: $dest) {
What are the cases where `dest` is set but not `addr`, and on the opposite side, `addr` is set but not `dest`?

2023-06-18 21:09 UTC, annando commented on src/Model/Item.php
> +	 * This does not apply to posts that are sent only in parallel to a group.
This is the difference between mentioning a group via `!` and `@`.

2023-06-18 21:14 UTC, annando commented on src/Module/Contact.php
> +				$header = DI::l10n()->t('Contacts');
From my point of view I find this much more readable, I must admit.

2023-06-18 21:15 UTC, MrPetovan commented on src/Module/Contact.php
> +				$header = DI::l10n()->t('Contacts');
Interestingly, PHP 8 has a structure to replace these verbose switch statements: https://www.php.net/manual/en/control-structures.match.php

2023-06-18 21:16 UTC, annando commented on src/Module/Magic.php
>  		if ($addr ?: $dest) {
Concerning this module: I don't know much about it. I'm just trying to fix stuff.

2023-06-18 21:17 UTC, annando commented
I will be on holiday for the next few days, so I cannot guarantee when I will address the comments.

Unrelated to this PR: Please don't forget my PR in the addons.

2023-06-18 23:09 UTC, MrPetovan commented on src/Module/Magic.php
>  		if ($addr ?: $dest) {
How do you test then?

2023-06-19 04:23 UTC, tobiasd commented on src/Model/Item.php
> +	 * This does not apply to posts that are sent only in parallel to a group.
Could you add the "@-mention" as explanation to the "parallel" (if that is meant).

2023-06-23 20:14 UTC, annando commented on src/Module/Magic.php
>  		if ($addr ?: $dest) {
I guess like you tested OStatus when you applied some changes :-)

2023-06-23 20:59 UTC, MrPetovan commented on src/Module/Magic.php
>  		if ($addr ?: $dest) {
So those are blind changes? I'm just trying to understand the purpose.

2023-06-23 21:02 UTC, annando commented on src/Module/Magic.php
>  		if ($addr ?: $dest) {
In fact, I made them a longer time ago and had to had a deeper look at it to know what the changes mean.

2023-06-23 21:08 UTC, annando commented on src/Model/Item.php
> +	 * This does not apply to posts that are sent only in parallel to a group.
Changed

2023-06-23 21:11 UTC, MrPetovan commented on src/Module/Magic.php
>  		if ($addr ?: $dest) {
Alrighty, let's leave this for future people to figure it out.

2023-06-23 21:12 UTC, MrPetovan approved these changes

2023-06-23 21:12 UTC, merged