[WIP] Introduce dynamic hook loading
friendica/friendica pull request #13246
Opened 2023-07-02 21:58 UTC by nupplaphil

- Dynamically load addon files
- Dynamically load hooks
- Rewrite Logger-logic to use new hook logic (Monolog is working again)

2023-07-17 16:06 UTC, MrPetovan requested changes
How do the hooks declared in this PR related to existing hooks?

2023-07-17 16:06 UTC, MrPetovan commented on bin/daemon.php
> +$dice = $dice->addRule(LoggerInterface::class,['constructParams' => [Logger\Capabilities\LogChannel::DAEMON]]);
```suggestion
$dice = $dice->addRule(LoggerInterface::class, ['constructParams' => [Logger\Capabilities\LogChannel::DAEMON]]);
```

2023-07-17 16:06 UTC, MrPetovan commented on bin/worker.php
> +$dice = $dice->addRule(LoggerInterface::class,['constructParams' => [LogChannel::WORKER]]);
```suggestion
$dice = $dice->addRule(LoggerInterface::class, ['constructParams' => [LogChannel::WORKER]]);
```

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Addon/Exception/AddonInvalidConfigFileException.php
> +	public function __construct($message = "", $code = 0, Throwable $previous = null)
```suggestion
	public function __construct($message = '', $code = 0, Throwable $previous = null)
```

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Hooks/Capabilities/ICanCreateInstances.php
> +	public function create(string $class, string $name, array $arguments = []): object;
```suggestion
	public function create(string $class, string $strategy, array $arguments = []): object;
```

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Hooks/Capabilities/ICanRegisterInstances.php
> +interface ICanRegisterInstances
Shouldn't it be `ICanRegisterStrategy`?

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Hooks/Capabilities/ICanRegisterInstances.php
> +	 * @param ?string $name      An arbitrary identifier for the given class, which will be used for factories, dependency injections etc.
For the given class or the given strategy?

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Hooks/Exceptions/HookConfigException.php
> +	public function __construct($message = "", \Throwable $previous = null)
```suggestion
	public function __construct($message = '', \Throwable $previous = null)
```

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Hooks/Util/HookFileManager.php
> +			$this->reloadHookConfig();
Shouldn't this be done in the constructor?

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Logger/Exception/LogLevelException.php
>  	public function __construct($message = "", Throwable $previous = null)
```suggestion
	public function __construct($message = '', Throwable $previous = null)
```

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Logger/Exception/LoggerArgumentException.php
>  	public function __construct($message = "", Throwable $previous = null)
```suggestion
	public function __construct($message = '', Throwable $previous = null)
```

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Logger/Exception/LoggerException.php
>  	public function __construct($message = "", Throwable $previous = null)
```suggestion
	public function __construct($message = '', Throwable $previous = null)
```

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Logger/Exception/LoggerUnusableException.php
>  	public function __construct($message = "", Throwable $previous = null)
```suggestion
	public function __construct($message = '', Throwable $previous = null)
```

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Logger/Factory/AbstractLoggerTypeFactory.php
> +				// legacy ALL
```suggestion
			// legacy ALL
```

2023-07-17 16:06 UTC, MrPetovan commented on src/Core/Logger/Factory/Logger.php
> +	public function create(ICanCreateInstances $createInstances, IManageConfigValues $config, Profiler $profiler): LoggerInterface
```suggestion
	public function create(ICanCreateInstances $instanceCreator, IManageConfigValues $config, Profiler $profiler): LoggerInterface
```

2023-07-17 16:06 UTC, MrPetovan commented on src/DI.php
> +	public static function loggCheck(): ICheckLoggerSettings
```suggestion
	public static function logCheck(): ICheckLoggerSettings
```

2023-07-17 18:16 UTC, nupplaphil commented
> How do the hooks declared in this PR related to existing hooks?

The existing hooks are all different kinds. This PR introduces the strategy hooks, which are used for dynamically load instance "strategies" for
- Cache
- Storage
- Lock
- Logger

Currently, the hook returns an array and you need to extract the instance out of an array-index, like

```php
$data = [
  'instance' => null,
  'name' => 'aName',
];

Hook::callAll('instance_creation', $data);

if ($data['instance'] !== null) {
   $instance = $data['instance'];
}
```

now, it's called:
```php
$instance = $instanceRegister->create(InstanceInterface::class, 'aName');
```

and instead of 
```php
Hook::register('instance_creation', 'aName_instance_creation()`);
```

you need to set at `{addon}/static/hooks.config.php` or `static/hooks.config.php`:
```php
   InstanceInterface::class => [
      ANameInstance::class => ['aName'],
   ],
```
which automatically gets registered at runtime.

2023-07-17 18:50 UTC, MrPetovan commented
I really would like to avoid the confusion between the existing data hooks and the new instance hooks. Can we just use the term "Strategies" instead of "Strategy Hooks"?

2023-07-17 21:24 UTC, nupplaphil commented
In the end, all hooks are replaced by either strategies, pipelines or events. But yes, this naming convention would work as well. But they should stay inside the hooks namespace, shouldn't it?

Or do you have a different common namespace in mind?

I see this pattern as a possibility for decoupling the core logic as well :-).

Events for one-way events to all listeners, pipelines for dynamically process content and strategies to choose different implementations.

But that's just a possibility, for now they should replace the `Hook` logic and corresponding table.

2023-07-17 22:46 UTC, MrPetovan commented
Ah, I see what you mean. In this case yes, the overarching Hook namespace still works. The transition might be a little confusing with a `hooks.config.php` that doesn't have anything to do with the current hooks.

2023-07-18 16:30 UTC, nupplaphil commented
Shall I rename it? I'm open to any suggestions :D

2023-07-18 16:36 UTC, MrPetovan commented
I'd rather we had a separate `strategies.config.php` file until we have all concepts under the same umbrella.

2023-07-21 20:42 UTC, nupplaphil commented on src/Core/Hooks/Capabilities/ICanRegisterInstances.php
> +	 * @param ?string $name      An arbitrary identifier for the given class, which will be used for factories, dependency injections etc.
yep, you're right

2023-07-21 20:43 UTC, nupplaphil commented on src/Core/Hooks/Util/HookFileManager.php
> +			$this->reloadHookConfig();
moved the load-routine to the dependency file

2023-07-23 02:34 UTC, nupplaphil commented
I'm finished here ;-)

2023-07-23 10:58 UTC, MrPetovan approved these changes

2023-07-23 10:58 UTC, merged