New functions for the language library
friendica/friendica pull request #13394
Opened 2023-09-03 17:52 UTC by annando

While coding PR #13390, I realized that we are using some language codes that aren't used by the language detection library. This means that languages like for example Danish or Finnish were never detected. Also some more languages are added, that we don't have got in our translations, but that might be used by our users and are detected by the library.

2023-09-03 21:14 UTC, MrPetovan requested changes

2023-09-03 21:14 UTC, MrPetovan commented on src/Core/L10n.php
> +				$langs = array_merge(['cy' => 'Cymraeg', 'uk' => 'Українська', 'pt-PT' => 'Português', 'zh-hant' => '繁體', 'fa' => 'فارسی'], $langs);
Please add each language on its separate line.

2023-09-04 01:37 UTC, annando commented on src/Core/L10n.php
> +				$langs = array_merge(['cy' => 'Cymraeg', 'uk' => 'Українська', 'pt-PT' => 'Português', 'zh-hant' => '繁體', 'fa' => 'فارسی'], $langs);
Done

2023-09-04 11:01 UTC, MrPetovan approved these changes

2023-09-04 11:01 UTC, merged