Channel visibility rules can now be set for each contact
friendica/friendica pull request #13442
Opened 2023-09-12 10:57 UTC by annando

We can now define per contact if we want to see more or less posts from them in the feeds or if we don't want to see their posts at all.

2023-09-14 00:15 UTC, MrPetovan reviewed
What’s the difference between default visibility and always?

2023-09-14 02:56 UTC, annando commented
In the "for you" channel, we only display every post of a contact, when we interact very often with that contact or if that option is activated for the contact. This rule is meant for contacts where you don't interact very much, but you want to see all posts anyway.

2023-09-14 20:00 UTC, MrPetovan commented
Ok. Since these choices are static and limited, please convert the select box to radio buttons like for the account types with descriptions like the one you just gave me.

2023-09-15 17:40 UTC, annando commented
Done

2023-09-15 18:02 UTC, MrPetovan requested changes
Now that I better understand the contact setting, I believe it should be named "frequency" instead of "visibility". We already have a "visibility" concept in Friendica shared with Mastodon regarding a post scope, either "Public" or  "Private", so I'd prefer if we picked a more accurate term for this feature.

2023-09-15 18:02 UTC, MrPetovan commented on src/Module/Contact/Profile.php
> +			'$visibility_label'       => $this->t('Visibility of this contact in appropriate channels'),
```suggestion
			'$visibility_label'       => $this->t('Frequency of this contact in relevant channels'),
```

2023-09-15 18:02 UTC, MrPetovan commented on src/Module/Contact/Profile.php
> +			'$visibility_description' => $this->t('Depending on the type of the channel not all posts from contacts are displayed by default. They for example need to have a certain amount of comments to be d
```suggestion
			'$visibility_description' => $this->t("Depending on the type of the channel not all posts from this contact are displayed. By default, posts need to have a minimum amount of interactions (comments, likes) to show in your channels. On the other hand there can be contacts who flood the channel, so you might want to see only some of their posts. Or you don't want to see their content at all, but you don't want to block or hide the contact completely."),
```

2023-09-15 18:02 UTC, MrPetovan commented on src/Module/Contact/Profile.php
> +			];
The `$channel_visibilities` variable won't be used anymore when the `$channel_visibility` template variable is removed for being unused.

2023-09-15 18:02 UTC, MrPetovan commented on src/Module/Contact/Profile.php
> +			$channel_visibilities   = null;
The `$channel_visibilities` variable won't be used anymore when the `$channel_visibility` template variable is removed for being unused.

2023-09-15 18:02 UTC, MrPetovan commented on src/Module/Contact/Profile.php
> +			'$visibility_default'     => ['channel_visibility', $this->t('Default visibility'), Contact\User::VISIBILITY_DEFAULT, $this->t('When activated, posts by this contact are displayed in the "for you"
```suggestion
			'$visibility_default'     => ['channel_visibility', $this->t('Default frequency'), Contact\User::VISIBILITY_DEFAULT, $this->t('Posts by this contact are displayed in the "for you" channel if you interact often with this contact or if a post reached some level of interaction.'), $channel_visibility == Contact\User::VISIBILITY_DEFAULT],
```

2023-09-15 18:02 UTC, MrPetovan commented on src/Module/Contact/Profile.php
> +			'$visibility_always'      => ['channel_visibility', $this->t('Display all posts of this contact'), Contact\User::VISIBILITY_ALWAYS, $this->t('If you follow this contact, then every post of this co
```suggestion
			'$visibility_always'      => ['channel_visibility', $this->t('Display all posts of this contact'), Contact\User::VISIBILITY_ALWAYS, $this->t('If you follow this contact, all their posts will appear on the "for you" channel'), $channel_visibility == Contact\User::VISIBILITY_ALWAYS],
```

2023-09-15 18:02 UTC, MrPetovan commented on src/Module/Contact/Profile.php
> +			'$visibility_always'      => ['channel_visibility', $this->t('Display all posts of this contact'), Contact\User::VISIBILITY_ALWAYS, $this->t('If you follow this contact, then every post of this co
```suggestion
			'$visibility_always'      => ['channel_visibility', $this->t('Display all posts'), Contact\User::VISIBILITY_ALWAYS, $this->t('If you follow this contact, then every post of this contact will appear on the "for you" channel'), $channel_visibility == Contact\User::VISIBILITY_ALWAYS],
```

2023-09-15 18:02 UTC, MrPetovan commented on src/Module/Contact/Profile.php
> +			'$visibility_never'       => ['channel_visibility', $this->t('Never display posts from this contact'), Contact\User::VISIBILITY_NEVER, $this->t('Posts from this contact will never be displayed in
```suggestion
			'$visibility_never'       => ['channel_visibility', $this->t('Never display posts'), Contact\User::VISIBILITY_NEVER, $this->t('Posts from this contact will never be displayed in any channel'), $channel_visibility == Contact\User::VISIBILITY_NEVER],
```

2023-09-15 19:13 UTC, annando commented
The changes are done.

2023-09-15 19:47 UTC, MrPetovan commented
Please rename the whole feature from “Visibility” (already used elsewhere i  the project) to “Frequency”. This includes variables, constants, class, methods and database field names.

2023-09-16 04:33 UTC, annando commented
I couldn't easily separate other changes to the code, so this PR now additionally contains an improvement for picking the post with the most activity when `FREQUENCY_REDUCED` is selected. Also it contains an improvement to the automatic reload for new content.

2023-09-17 12:35 UTC, MrPetovan requested changes

2023-09-17 12:35 UTC, MrPetovan commented on src/Model/Contact/User.php
> +		$visibility = self::FREQUENCY_DEFAULT;
```suggestion
		$frequency = self::FREQUENCY_DEFAULT;
```

2023-09-17 12:35 UTC, MrPetovan commented on src/Model/Contact/User.php
> +				$visibility = $public_contact['channel-frequency'] ?? self::FREQUENCY_DEFAULT;
```suggestion
				$frequency = $public_contact['channel-frequency'] ?? self::FREQUENCY_DEFAULT;
```

2023-09-17 12:35 UTC, MrPetovan commented on src/Model/Contact/User.php
> +		return $visibility;
```suggestion
		return $frequency;
```

2023-09-17 12:35 UTC, MrPetovan commented on src/Model/Contact/User.php
> +	 * Returns the channel visibility state for contact id and user id
```suggestion
	 * Returns the channel frequency state for contact id and user id
```

2023-09-17 12:35 UTC, MrPetovan commented on src/Module/Conversation/Network.php
> +		// Upon updates in the background and order by last comment we order by receive date,
```suggestion
		// Upon updates in the background and order by last comment we order by received date,
```

2023-09-17 12:35 UTC, MrPetovan commented on src/Model/Contact/User.php
I realized that this class should actually be moved to `src/Model/User/Contact.php` to match both the database table name and the intent in English, but it doesn't need to be done in this PR.

2023-09-17 17:43 UTC, annando commented on src/Model/Contact/User.php
> +		$visibility = self::FREQUENCY_DEFAULT;
Done

2023-09-17 17:43 UTC, annando commented on src/Model/Contact/User.php
> +				$visibility = $public_contact['channel-frequency'] ?? self::FREQUENCY_DEFAULT;
Done

2023-09-17 17:43 UTC, annando commented on src/Model/Contact/User.php
> +		return $visibility;
Done

2023-09-17 17:43 UTC, annando commented on src/Model/Contact/User.php
> +	 * Returns the channel visibility state for contact id and user id
Done

2023-09-17 17:44 UTC, annando commented on src/Module/Conversation/Network.php
> +		// Upon updates in the background and order by last comment we order by receive date,
Done

2023-09-17 17:46 UTC, annando commented on src/Model/Contact/User.php
I must admit, I want to continue with the channels.

2023-09-17 17:55 UTC, MrPetovan approved these changes

2023-09-17 17:55 UTC, merged