There is now a time limit when fetching AP endpoints
friendica/friendica pull request #13473
Opened 2023-09-28 08:06 UTC by annando

Some accounts have got huge lists of followers. This can result in fetching the contacts for a long time. We now automatically stop after one minute of fetchting to not stress the remote system more than we have to.

2023-09-28 18:50 UTC, MrPetovan requested changes

2023-09-28 18:50 UTC, MrPetovan commented on src/Protocol/ActivityPub.php
> +	 * @param integer $timestamp Internally used parameter to stop fetching after some time
Please rename to `start_timestamp`.

2023-09-29 04:53 UTC, annando commented on src/Protocol/ActivityPub.php
> +	 * @param integer $timestamp Internally used parameter to stop fetching after some time
Done

2023-09-29 07:30 UTC, MrPetovan approved these changes

2023-09-29 07:30 UTC, merged