Flip replyto link
friendica/friendica pull request #13527
Opened 2023-10-09 05:43 UTC by xundeenergie

Resolves #13524 and #13520

2023-10-09 17:10 UTC, Raroun commented
Just a question:
Is it possible that "reply to" shows up on transifex to be translated? :)

2023-10-09 18:09 UTC, xundeenergie commented
> Just a question: Is it possible that "reply to" shows up on transifex to be translated? :)

It's made translateable, as all other text too, for tranisflex.

2023-10-09 18:15 UTC, xundeenergie commented
The new text for comments without parents:

on small screen:
![Bildschirmfoto vom 2023-10-09 20-05-49](https://github.com/friendica/friendica/assets/5894829/8f14f56b-c296-4efb-bfad-afe0620c4eb1)

and on wide screen
![Bildschirmfoto vom 2023-10-09 20-06-33](https://github.com/friendica/friendica/assets/5894829/3ac41e71-db92-4fff-95df-bfb49d61ccde)

2023-10-09 18:39 UTC, xundeenergie commented
Btw... this is such a comment
https://soc.schuerz.at/display/67d0f1d0-abb2c986d4e1ba42-5ddcaaba

And i don't know, why messages.po_check failed...

i merged 2023.09-rc into this branch, run bin/run_xgettext.sh and committed all.
Then i pushed to github.

What's wrong?

2023-10-11 11:38 UTC, MrPetovan commented
Maybe another pull request was merged in the meantime, which triggers the merge conflict? In doubt, do the merge + script execution again.

2023-10-11 12:24 UTC, xundeenergie commented
I've done the merge and commit again.

2023-10-11 13:49 UTC, MrPetovan requested changes

2023-10-11 13:49 UTC, MrPetovan commented on src/Object/Post.php
> +			'isreplyto'       => DI::l10n()->t('is reply to %s', $parent_username),
Please keep the `in reply to` translation. Additionally, please rename all `isreplyto` variables and array keys to `inreplyto` to match the translation string change.

2023-10-11 13:49 UTC, MrPetovan commented on src/Object/Post.php
> +			'isunknown_label' => DI::l10n()->t('parent is probably private or not federated'),
```suggestion
			'isunknown_label' => DI::l10n()->t('Parent is probably private or not federated.'),
```

2023-10-11 13:55 UTC, xundeenergie commented on src/Object/Post.php
> +			'isreplyto'       => DI::l10n()->t('is reply to %s', $parent_username),
Ok.
But why? 
It sounds strange to my ears...

2023-10-11 15:04 UTC, xundeenergie commented on src/Object/Post.php
> +			'isreplyto'       => DI::l10n()->t('is reply to %s', $parent_username),
i changed it and all occurances

2023-10-11 17:44 UTC, MrPetovan commented on src/Object/Post.php
> +			'isreplyto'       => DI::l10n()->t('is reply to %s', $parent_username),
Thanks, the (American-)English expression is "in reply to" as evidenced in the Mail header In-Reply-To. You could also say "This is a reply to" but it's longer and requires a subject that "in reply to" naturally implies.

2023-10-11 17:47 UTC, MrPetovan requested changes

2023-10-11 17:47 UTC, MrPetovan commented on src/Object/Post.php
> +		$parent_unknown  = $parent_username ? '' : DI::l10n()->t('parent unknown');
```suggestion
		$parent_unknown  = $parent_username ? '' : DI::l10n()->t('Unknown parent');
```

2023-10-11 18:47 UTC, MrPetovan commented
Thank you for the change, you will have to regenerate the messages.po file.

2023-10-11 20:03 UTC, MrPetovan approved these changes

2023-10-11 20:03 UTC, merged