Fix images in the API
friendica/friendica pull request #13525
Opened 2023-10-08 19:56 UTC by annando

This fixes the problem that pictures that had been served via the API had been published without the host. This resulted in the clients not displaying pictures anymore.

2023-10-08 21:02 UTC, MrPetovan requested changes
This is the wrong approach. The base URL should be prepended when it's necessary instead of adding yet more calls to `DI::baseUrl`. Besides, it would double the base URL in the places where I already did the prepending.

2023-10-09 02:27 UTC, annando commented
From what I can see, the functions `getUrlForId` and `getPreviewUrlForId` are only called by the API. There we have to serve full URLs including the host. I don't see a reason for having to add some functionality at the places where we call these functions to add the host there, when we can make this at the root.

2023-10-10 13:16 UTC, MrPetovan commented
Ah, never mind, I confused these with `Entity\PostMedia->getPreviewPath` and `getPhotoPath`. Calls to these methods should eventually replace calls to the methods you modified but it isn't the time nor the place in this PR.

2023-10-10 13:16 UTC, MrPetovan approved these changes

2023-10-10 13:16 UTC, merged