Leftovers from pr #13339
friendica/friendica pull request #13582
Opened 2023-10-27 09:48 UTC by Raroun

PR#13339 has left some residue, which I would like to clean up and clear up any misunderstandings between "first and last name" and display name.
I am aware that we do not usually change source strings, but I have not found any other way.

2023-10-27 12:56 UTC, Raroun commented
i don´t know why messages.po is failing -.-

2023-11-01 01:19 UTC, MrPetovan requested changes
Changing source strings is fine if the meaning changes like in this case. On the other hand typos shouldn't be fixed in source strings.

2023-11-01 01:19 UTC, MrPetovan commented on src/Module/Admin/Site.php
> +			'$enable_regfullname'     => ['enable_regfullname', DI::l10n()->t('Enable Fullname check'), !DI::config()->get('system', 'no_regfullname'), DI::l10n()->t('Check the box to only allow users to regi
```suggestion
			'$enable_regfullname'     => ['enable_regfullname', DI::l10n()->t('Enable full name check'), !DI::config()->get('system', 'no_regfullname'), DI::l10n()->t('Prevents users from registering with a display name with fewer than two parts separated by spaces.')],
```

2023-11-01 01:19 UTC, MrPetovan commented on static/settings.config.php
> +		// Allow pseudonyms (true) or allow users to register which display name consists of at least two strings, as an anti spam measure (false).
```suggestion
		// Allow users to register with a display name comporting fewer than two parts separated by spaces.
```

2023-11-01 13:34 UTC, MrPetovan commented
Now that you've included my suggested changes, you should re-generate the `messages.po` file using the `bin/run_xgettext.sh` script.

2023-11-01 14:02 UTC, Raroun commented
thanks, i was unsure because messages.po allways fails in the code checks.

2023-11-01 14:10 UTC, MrPetovan commented
It comes from a discrepancy between the gettext version that's used in the Continuous Integration pipeline. 🤷‍♂️

2023-11-01 14:10 UTC, MrPetovan approved these changes

2023-11-01 14:10 UTC, merged