Distribute incoming posts according to the parent followers collection
friendica/friendica pull request #13687
Opened 2023-12-01 09:57 UTC by annando

This improves PR #13684. That one had got issues under several conditions. It is now reworked, so that we don't need to rely upon the HTTP signer anymore (which was problematic).

2023-12-01 16:06 UTC, MrPetovan requested changes

2023-12-01 16:06 UTC, MrPetovan commented on src/Protocol/ActivityPub/Receiver.php
> +		//		}
Wrong indentation.

2023-12-01 20:24 UTC, annando commented on src/Protocol/ActivityPub/Receiver.php
> +		//		}
I removed the old code.

2023-12-02 08:42 UTC, MrPetovan approved these changes

2023-12-02 08:42 UTC, merged