The "summary" has now a dedicated field when creating and editing posts
friendica/friendica pull request #14019
Opened 2024-03-21 08:11 UTC by annando

The "summary" field that is used in Mastodon as "content warning" can now be edited more easily. This is a feature that has to be enabled by the user.

2024-03-21 11:56 UTC, MrPetovan requested changes

2024-03-21 11:56 UTC, MrPetovan commented on src/Module/Item/Compose.php
> +				'placeholdersummary'   => Feature::isEnabled(DI::userSession()->getLocalUserId(), 'summary') ? $this->l10n->t('Set summary') : '',
This placeholder isn't helpful if the "Summary" field ends up being used as content warning.

2024-03-21 11:56 UTC, MrPetovan commented on src/Module/Post/Edit.php
> +			'$placeholdersummary'  => (Feature::isEnabled($this->session->getLocalUserId(), 'summary') ? $this->t('Set summary') : ''),
Set concern here over placeholder wording.

2024-03-21 11:56 UTC, MrPetovan commented on src/Content/Feature.php
> +				['summary',    DI::l10n()->t('Summary'),         DI::l10n()->t('Add a summary to your posts'), false, DI::config()->get('feature_lock', 'summary', false)],
Same concern here, there's no explanation of the end result for this summary.

2024-03-21 13:29 UTC, annando commented
Is your concern that it isn't mentioned that the field is used as "content warning" over on Mastodon? I try to act in some limbo here, because I wouldn't want to enforce the usage of their "content warning" here as well.

2024-03-21 16:15 UTC, MrPetovan commented
What do we do when we receive the "summary" field from a remote server? If we render it as a content warning no matter the origin platform, then we should be clear about that in the placeholder.

2024-03-22 04:36 UTC, annando commented
I just had a look at other systems. On Pleroma that field is called "subject":
![image](https://github.com/friendica/friendica/assets/844208/0d5b1193-8a6f-49e2-a934-fab4ba60dbc0)
On Misskey it is "comments":
![image](https://github.com/friendica/friendica/assets/844208/98e3f9a3-809e-4873-abc9-20befd1bf765)
Hubzilla calls it "Summary":
![image](https://github.com/friendica/friendica/assets/844208/4c6b0016-4e3b-4606-ab37-c43a1fd61465)
Solely Mastodon calls it "Content Warning":
![image](https://github.com/friendica/friendica/assets/844208/6feb1b88-ab46-4a61-9b8a-ce83ee17955b)

2024-03-22 13:38 UTC, MrPetovan commented
The ActivityPub protocol is completely hidden from end-users so I don't think it's relevant to use the protocol terminology in a user-facing form. I think we should stick to the main use for this field. Even if it's called differently in other platforms than Mastodon, if it is still displayed as content warning on those platforms, we should call it "content warning".

2024-03-22 14:22 UTC, annando commented
I completely dislike the word "content warning", since there is a lot of politics around this word and their usage. I prefer to stick to a much more neutral description.

2024-03-22 14:26 UTC, MrPetovan commented
I respect your personal opinion, but I don't think it is relevant here. If the main outcome of this field is being used as a content warning on various remote platforms, then we should label it content warning in the form and let users choose to use it or not.

2024-03-29 09:14 UTC, loma-one commented
I agree with Michael's assessment. The term "content warning" is mutating into a fighting term. It also doesn't describe what this field actually is. In my view, it is a summary of longer content that describes what is to be expected in a value-neutral way. This is how I have always understood it in Friendica and used it in this sense. 


My wish for the field name "Summary" in German "Zusammenfassung"

2024-03-29 09:44 UTC, rausgerufen commented
I also think that the term "content warning" is not appropriate. It comes across as a bit combative and I agree with annando and loma-one. 

I would prefer the term for the field name "Summary" in German "Zusammenfassung"

2024-03-29 10:14 UTC, kr428 commented
I'm on the "Summary" side of the fence here too. Maybe we can hide a hint somewhere (tooltip?) that this will be used as Content Warning in some platforms?

2024-03-29 10:35 UTC, B0ngripper commented
I don't like the label "content warning" either. "Summary" is much better and would also fit the purpose.

2024-03-29 11:19 UTC, tobiasd commented
I'm in favor of "Summary" as well, as only one platform is using the CW term and I'm much more inclined to write a summary about my 500 words report of an event so people can decide to read the rest of the report then to write a content warning about a totally harmless event.

2024-03-30 02:52 UTC, MrPetovan commented
It isn't just one platform that uses the `summary` ActivityPub field to populate the content warning feature. Mastodon definitely started the trend, but many other platforms took after Mastodon and now it's a de facto standard across the Fediverse.

If the form field is named "Summary", it will still appear as a content warning on most other federated platforms. It will even appear as a content warning right here on Friendica by default.

Again, I'm not discussing how polarizing the content warning feature is nor advocating users to use it or not, I just believe we should be as accurate as possible about the end result of that field, and currently it is being used as a content warning on most AP-compatible platforms.

2024-03-30 05:23 UTC, loma-one commented
@MrPetovan I can only partially understand your argument. For example, Mastodon has introduced a de facto limit of 500 characters. Friendica and many other projects have nevertheless decided to continue to support more than those 500 characters. 
Misdeclaring something and enforcing it with great market power doesn't make it any more right. Perhaps @kr428's suggestion of an appropriate note will help.

2024-03-30 05:40 UTC, MrPetovan commented
@loma-one Your argument would hold better if we weren't one of those projects that align with Mastodon on the functional use of the `summary` field as content warning. We don't copy everything from Mastodon, but we did copy this one feature to satisfy majority expectations both from incoming Mastodon (and other platforms) posts and for outgoing posts, including to these platforms as well.

Labeling this field "Content Warning" is the most accurate path we can take, because "Summary" is only accurate technically and doesn't say anything about how the field is actually used. If we need an additional tooltip on top of "Summary" to explain what the field actually does, what's the point of "Summary"?

2024-03-30 06:36 UTC, tobiasd commented
> if we weren't one of those projects that align with Mastodon on the functional use of the summary field as content warning

Which is a mistake that should be corrected.

2024-03-30 07:22 UTC, kr428 commented
Stupid question as I don't know: Did that Summary field happen to already be around in pre-Mastodon Friendica/Hubzilla? And, is this something that has seen a regular use for, well, containing article summaries for longer posts?

2024-03-30 08:14 UTC, loma-one commented
@MrPetovan First of all, thank you for the constructive discussion of the topic. 

Hubzilla and other projects orientated as macroblogs are going their own way here. Which also makes sense from my personal point of view, because it is an independent way of dealing with content. 

In this context, I had a look at how Mozilla defines the field. They talk about details there. I can't find the term "Content Warning" in any official specification. This may be helpful:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details?retiredLocale=de

2024-03-30 13:57 UTC, annando commented
@MrPetovan the work "content warning" is politically burned at least in the German Mastodon sphere. There are huge discussion about this topic, people are blocked or move servers because of that ...

I don't want to get sucked into these discussions. Also I don't want people to believe that they have to use this field for their posts. In my PR I use the words "summary" and "spoiler" to describe the functionality.

2024-03-30 14:08 UTC, MrPetovan commented
> Which is a mistake that should be corrected. At least for me it is as simple as this.

Why is it a mistake? Friendica is by design in-between macro-blogging and micro-blogging, so there's no obvious way we should be displaying this field. Also our relevance as a social media project has always been tied to larger platforms/networks, so we've been following remote practices for a long time because we can't rely on our bespoke network that we abandoned the moment we dropped support for DFRN.

> Stupid question as I don't know: Did that Summary "concept" happen to already be around in pre-Mastodon Friendica/Hubzilla? And, is this something that has seen a regular use for, well, containing article summaries for longer posts?

We used to support it in the `[abstract]` BBCode tag. And now I wonder how this "summary" field that's AP-specific appears in outgoing Diaspora posts.

> Hubzilla and other projects orientated as macroblogs are going their own way here.

Hubzilla is indeed way more opinionated than Friendica and has lower adoption as a result. I personally was warded off that project because how unfamiliar it was for me. On the other hand Friendica has been trying to be closer to the popular AP implementations for affordance reasons.

> In this context, I had a look at how Mozilla defines the field. They talk about details there. I can't find the term "Content Warning" in any official specification. This may be helpful:

This is the description of the `<summary>` HTML tag which is not exactly what is discussed here (the ActivityPub `summary` field) but is coincidentally part of the collapsed-by-default panel feature that is called "Content Warning" throughout the Fediverse. And I don't think labeling this new form field "Disclosure Element" to match the HTML specification would fare any better.

2024-03-30 14:23 UTC, annando commented
@MrPetovan it is not "throughout the Fediverse", it is just Mastodon that names and uses it that way. My ideas for the future are that this field can then be used as a replacement for the "abstract" BBCode to use it as the text when we post to connector networks with limited character counts like Bluesky.

2024-03-30 14:29 UTC, tobiasd commented
> >    Which is a mistake that should be corrected. At least for me it is as simple as this.
>
> Why is it a mistake

Because the field was not intended to be used exclusively as a warning about potentially triggering content. By labeling it as content warning, people who do not think that their content needs to be warned about will not use it, even though they might consider writing a short summary about their lengthily content.

The entire CW logic is bogus for me as the author cannot know what triggers their audience. Users should be empowered to filter out content by their own rules based on their own triggers. Based on the categories (tags) and the content of the posting. A summary of the content that follows might contain hints for the triggers without directly showing them, but cannot contain all.

2024-03-30 15:51 UTC, kr428 commented
> 
> The entire CW logic is bogus for me as the author cannot know what triggers their audience. Users should be empowered to filter out content by their own rules based on their own triggers. Based on the categories (tags) and the content of the posting. A summary of the content that follows might contain hints for the triggers without directly showing them, but cannot contain all.

Though I generally share that opinion, I'm thinking of a spoiler alert as a more obvious use case: If, in example, writing a movie review and revealing its plot to the readers, this is something I'd like to know in advance, and this information also is probably different to what to expect in a summary/synopsis that (in my understanding) outlines the most important points in a more lengthy text for those who don't want to read through all of that. From that perspective I wonder whether summary and spoiler alert (to avoid the somewhat "burnt" term CW for now) seem quite different things that need different handling...?

2024-03-30 16:11 UTC, MrPetovan commented
> it is not "throughout the Fediverse", it is just Mastodon that names and uses it that way.

"Just" is load-bearing here, as Mastodon still constitutes 50% of the observable Fediverse servers, and almost 75% of the reported users. Besides, how is the field used by the runner-ups, namely Pleroma, Akkoma, MissKey, PeerTube and Lemmy? More importantly, how do we currently use the field in posts received from these platforms?

> My ideas for the future are that this field can then be used as a replacement for the "abstract" BBCode to use it as the text when we post to connector networks with limited character counts like Bluesky.

The `[abstract]` tag allowed to target specific platforms, and it doesn't look like this field will be able to be platform-specific, potentially resulting in expectations mismatch.

> they might consider writing a short summary about their lengthily content

I don't believe anybody is considering writing a short summary about their lengthily content without a clear knowledge of where and how this summary will display. I do that for my blog posts because I know exactly where this summary is going to show (in the post list). Simply labeling the field "Summary" isn't enough to convey how it's currently used, which is as a content warning. Even the type of field @annando chose for it (single-line text field) isn't congruent with the paragraph-length summaries usually are.

> The entire CW logic is bogus for me as the author cannot know what triggers their audience.

I agree with you but again, I don't believe it's relevant to the matter at hand. We have been using this field as a content warning for years now, even if it was initially a mistake we have gone pretty far down this road and I don't believe we can walk it back without confusing or annoying users.

2024-03-31 16:33 UTC, loma-one commented
@MrPetovan 
> We have been using this field as a content warning for years now, even if it was initially a mistake we have gone pretty far down this road and I don't believe we can walk it back without confusing or annoying users.

That is their personal interpretation of the field. For me and many in my immediate environment who actively work with Friendica or Hubzilla, it is a summary. It has never been used in any other way.

2025-07-10 18:32 UTC, marcusxss commented
Could the way it's displayed in the UI describe both use cases for it, say:
"Summary  / Content warning"    OR 
"Summary / Content note"   OR
"Summary (Content note)"
?

That is if "Content note" doesn't sufficiently describe both use cases, which I guess could also be an option, if it's mainly the "warning" part that the disagreement is about.

Edit: Just to clarify, "Content note" is not just a term I made up - from Cambridge University:
https://www.cctl.cam.ac.uk/content-notes/what-are-content-notes

I know for some, it's also preferred over "Content warning".

2025-07-12 09:02 UTC, loma-one commented
If I see it correctly, then the dilemma of this draft could be cured by this FEP https://codeberg.org/fediverse/fep/src/branch/main/fep/b2b8/fep-b2b8.md, right?

2025-08-06 00:18 UTC, mfxa commented
Note to the future:
Once this is resolved and merged in some form, please reopen this PR #15061

2025-08-10 07:05 UTC, loma-one commented
@annando 
Mastodon can now handle summaries. Therefore, it makes sense for Friendica to now have its own field where users can create and send summaries.

Since the last release, Mastodon seems to distinguish between [abstract] = _Content Warning_ and [abstract=apub] = _Summary_.

Created as an article
<img width="598" height="537" alt="grafik" src="https://github.com/user-attachments/assets/a75b4fd8-f379-48de-95d1-f1dbeb79b723" />

Created as a note
<img width="598" height="567" alt="grafik" src="https://github.com/user-attachments/assets/fbc9e8bf-5e6c-4ba3-9d40-c70e5039512e" />

I think it would be really great if this issue could be resolved for Friendica.

2025-08-12 16:39 UTC, loma-one commented
@mfxa 
Could the way it's displayed in the UI describe both use cases for it, say:
"Summary  / Content warning"    OR 
"Summary / Content note"   OR
"Summary (Content note)"
?

**My observation:** 
- Marking content with [abstract] without further network information will continue to result in a content warning. **Posts marked in this way will be hidden if the user so desires.**
- Tagging with network information, for example: [abstract=apup] for ActivityPub, causes the content to be displayed as a summary in Mastodon and other systems in the Fediverse. The long text behind the summary is set to a link. **The post is not hidden, even if CW is activated by the user.**
- Different labels can be used to transfer different summaries to different networks:
-- [abstract=bskl] = Bluesky, 
-- [abstract=dspr] = Diaspora, etc.
- Based on my observations, the abstract can be combined with the CW label and as a summary (even if that probably wouldn't make sense).
<img width="689" height="725" alt="grafik" src="https://github.com/user-attachments/assets/29cb12c8-4980-4b7f-a694-c432fefe9dd3" />

You can see the result for yourself on various platforms using this example: https://loma.ml/display/373ebf56-1968-9b5d-cb94-075508735186

2025-09-20 13:26 UTC, marcusxss commented
Great to see this may make the RC! :partying_face: 

I'm wondering a little if this field couldn't just be enabled for everyone, instead of a user setting?
It could be a textarea and then set to `text-autosize` so it just starts out only taking up a single line, expanding with more lines as the user types.

2026-03-02 14:22 UTC, MrPetovan commented on view/theme/frio/templates/jot.tpl
> +					{{if $placeholdersummary}}{{include file="field_checkbox.tpl" field=$sensitive}}{{/if}}
Why is the sensitive setting dependent on the Summary feature being enabled?

2026-03-02 14:42 UTC, annando commented on view/theme/frio/templates/jot.tpl
> +					{{if $placeholdersummary}}{{include file="field_checkbox.tpl" field=$sensitive}}{{/if}}
You are right. This could be enabled all the time. I will change that.

2026-03-02 16:26 UTC, annando commented on view/theme/frio/templates/jot.tpl
> +					{{if $placeholdersummary}}{{include file="field_checkbox.tpl" field=$sensitive}}{{/if}}
is changed

2026-03-02 17:01 UTC, MrPetovan approved these changes

2026-03-02 17:01 UTC, merged

2026-03-02 21:02 UTC, marcusxss commented
Now this has been merged :partying_face: , should we just remove the BBCode content warning/abstract buttons, when creating and editing posts?:
<img width="662" height="156" alt="image" src="https://github.com/user-attachments/assets/ed892a95-e3d2-4e1b-957a-d1b00d5c1d57" />

2026-03-02 21:34 UTC, MrPetovan commented
@marcusxss No, since it's an optional feature that must be enabled by an administrator.

2026-03-02 21:49 UTC, marcusxss commented
Okay, it was also because the that bbcode version is not fully working, as one can only add it and not modify it afterwards, or edit a new one in later. I could make a PR to remove it from the edit form as suggested in #15061, and then it's left in the new post form?

2026-03-02 22:07 UTC, MrPetovan commented
I'm not sure what you are talking about, but I'm always happy about people submitting work!