Some more deprecated function calls are replaced
friendica/friendica pull request #14157
Opened 2024-05-14 08:38 UTC by annando

Several more function calls are now replaced and some legacy functions are completely removed now.

2024-05-14 18:30 UTC, MrPetovan requested changes
Good job, it looks like `BaseModule` could use a `UserSession` dependency, but it will take a fair bit of work to get it in given the inheritance graph.

2024-05-14 18:30 UTC, MrPetovan commented on src/Module/Contact/Profile.php
> +use Friendica\Contact\LocalRelationship\Entity\LocalRelationship as EntityLocalRelationship;
Please rename the alias to `LocalRelationshipEntity` to satisfy the English order of qualifier.
```suggestion
use Friendica\Contact\LocalRelationship\Entity\LocalRelationship as LocalRelationshipEntity;
```

2024-05-14 19:22 UTC, annando commented
Yeah, there will be some work to get rid of `DI` in these classes.

2024-05-14 19:23 UTC, MrPetovan approved these changes

2024-05-14 19:23 UTC, merged

2024-05-15 05:20 UTC, tobiasd commented on src/App.php
> -	public function getLoggedInUserNickname(): string
This seems to be used by the calendar, see https://github.com/friendica/friendica/issues/14025#issuecomment-2111605062