SVG icons for various fediverse systems
friendica/friendica pull request #14527
Opened 2024-11-02 16:14 UTC by annando

This PR adds a list of SVG icons for nearly all known fediverse systems. This replaces the "Fork Awesome" symbols for these systems.

This PR is currently a draft since adding licensew information for all these files is quite a heavy task.

2024-11-03 19:55 UTC, Art4 commented
@annando Can't you using the REUSE tool for licensing? https://reuse.software/dev/

2024-11-06 07:42 UTC, annando commented
@Art4 sure, `reuse` tells me, where I have to add a license. But then I have to investigate which licenses apply.

2024-11-06 08:08 UTC, tobiasd commented
> @annando Can't you using the REUSE tool for licensing? https://reuse.software/dev/

We use it for our license check, but it does only check for a license for the file in the repository, not for *finding the source of the file and check there for the information* (which would be really cool feature I should really request x)). Sadly this information on other projects repos is well hidden.

2024-11-06 08:19 UTC, Art4 commented
OK, I understand the problem. Thank you for explanation.

2024-11-06 08:29 UTC, annando commented
I now switched to mostly icons from Wikimedia. There is always license information. "Only" thing I have to do now is to understand how this has to assigned.

2024-11-07 23:03 UTC, MrPetovan approved these changes
This looks good to me, although I'm not a copyright lawyer.

2024-11-08 06:00 UTC, Art4 requested changes
Great work. :+1: Just two line breaks are missing.

2024-11-08 06:00 UTC, Art4 commented on images/platforms/diaspora.svg.license
> +SPDX-License-Identifier: CC0-1.0
Missing line break
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2024-11-08 06:00 UTC, Art4 commented on images/platforms/hubzilla.svg.license
> +SPDX-License-Identifier: CC0-1.0
Missing line break
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2024-11-08 09:45 UTC, annando commented on images/platforms/hubzilla.svg.license
> +SPDX-License-Identifier: CC0-1.0
Changes

2024-11-08 15:11 UTC, MrPetovan approved these changes

2024-11-08 15:12 UTC, merged