Message split at commas, exclamation mark or question mark
friendica/friendica pull request #14549
Opened 2024-11-12 09:55 UTC by annando

This is a further enhancement of the split functionality. Now messages are also split at sentences that end with `!` or `?`. Also we split at a comma when there is no other possibility.

2024-11-12 13:14 UTC, MrPetovan requested changes
Please add tasteful tests cases with the new rules you added to splitting. Let me know if you need a starting point.

2024-11-12 14:06 UTC, annando commented
Tasteful? I've got some Indian spices, for example Garam Masala. Is this tasteful enough? 😁 

I will have a look at it in the next days.

2024-11-14 14:43 UTC, annando commented
@MrPetovan done.

2024-11-14 20:35 UTC, MrPetovan approved these changes

2024-11-14 20:35 UTC, merged