Preparation für multiple icon styles / improved code
friendica/friendica pull request #14541
Opened 2024-11-09 14:42 UTC by annando

This PR contains the preparation for multiple styles, so you don't only have got the coice between "color" and "black".

Also the whole code is rewritten and improved.

2024-11-09 18:05 UTC, MrPetovan requested changes

2024-11-09 18:05 UTC, MrPetovan commented on images/platforms/color/sharkey.license
This file should be renamed to `sharkey.svg.license` to follow the convention used in this folder.

2024-11-09 22:21 UTC, annando commented on images/platforms/color/sharkey.license
The file is removed.

2024-11-09 22:41 UTC, annando commented
I now added the icons from https://codeberg.org/FediverseIconography/pages This should now be a mostly complete list.

2024-11-10 19:53 UTC, annando commented
Now white icons are added as well.

2024-11-10 20:51 UTC, MrPetovan approved these changes

2024-11-10 20:51 UTC, merged