Refactoring of app class
friendica/friendica pull request #14542
Opened 2024-11-10 08:21 UTC by Art4

This is the first part of the refactoring plan from #14535. The goal is that the class `Friendia\App` is only used in the `index.php`.

In this PR I extracted all methods from the App class, that are called outside the index.php into a new `AppLegacy` class and deprecate the methods in the App class.

Next I've create a new `Friendica\AppHelper` interface that is now implemented by `App` and by `AppLegacy` class. I created a new Dice rule for `AppHelper` that returns the `AppLegacy` instances. I also created a new `DI::apphelper()` method to get the AppLegacy instance.

In the next step replaced every call for the App class with the AppHelper interface.

2024-11-10 11:29 UTC, Art4 commented
I'm a little bit confused about the ci/woodpecker/pr/code_standards_check pipeline: In woodpecker it shows me CS errors in 4 files. But if I run php-cs-fixer on my own using `bin/composer.phar run cs:check` I get 642 files. This is very demotivating because I cannot simply run `bin/composer.phar run cs:fix`, but have to go manually through all files and make the fixes.

2024-11-10 18:32 UTC, nupplaphil commented
Hi, the code_standard_checks is "just" checking the code standard of the changed files during the PR, based on
https://github.com/friendica/friendica/blob/c8a4b67414cbeb67d1875b9b28aadf4d3b1d10ab/.woodpecker/.code_standards_check.yml#L38-L40

If you execute it without the `CHANGED_FILE` variable, it will check the whole codebase :)

2024-11-10 20:58 UTC, Art4 commented
@nupplaphil Is there a reason why the code style in many of the files is not fixed? Otherwise I would create some PRs to fix this.

2024-11-10 21:01 UTC, nupplaphil commented
Yes, we decided years ago that it would be a better idea to fix it PR per PR instead of a big bang - to reduce the possible high amount of regressions.

2024-11-10 21:09 UTC, Art4 commented
> Yes, we decided years ago that it would be a better idea to fix it PR per PR instead of a big bang - to reduce the possible high amount of regressions.

Hmm, I see. Having a style guide and rules for CS fixer makes it easy to produce code upfront without thinking to much about the code style, because afterwards one could simply run one command to fix everything. This approach doesn't work here because of the many unfixed files.

I recommend to clean this up. If it is ok, then I would create several PRs for this. This would also reduce the entry barriers for new developers.

2024-11-10 23:05 UTC, annando commented
Cleaning is okay, only the individual PRs shouldn't be huge.

2024-11-11 05:09 UTC, annando commented
Just one thing: Please take into account that we are currently working in parallel on the RC branch and the develop branch. So before refactoring whole parts of the code, maybe we already should merge all RC changes into the develop branch (something that we normally do upon the release). Otherwise this would cause really massive merge conflicts.

2024-11-11 08:48 UTC, Art4 commented
> Just one thing: Please take into account that we are currently working in parallel on the RC branch and the develop branch. So before refactoring whole parts of the code, maybe we already should merge all RC changes into the develop branch (something that we normally do upon the release). Otherwise this would cause really massive merge conflicts.

@annando Yes, I had exactly the same thoughts yesterday. It would be best if there was a port to the `develop` branch always after a merge into the `2024.09-rc` branch. Should I create a PR for this?

2024-11-11 09:52 UTC, annando commented
I'm not totally sure how @tobiasd is doing this (he normally manages the branches upon release). So let's wait for him.

2024-11-12 07:32 UTC, Art4 commented
@annando If I've [seen this correct](https://github.com/friendica/friendica/commits/develop/?since=2024-08-17&until=2024-08-18) @tobiasd first merged the rc-branch into the `stable` branch. Next the `stable` branch was merged into the `develop` branch.

If I create a PR to merge the `2024.09-rc` into the `develop` branch now this will save @tobiasd a lot of work in the later merge.

2024-11-16 18:03 UTC, MrPetovan commented
Please rebase your PR now that the RC branch has been merged into develop.

2024-11-17 07:40 UTC, Art4 commented
> Please rebase your PR now that the RC branch has been merged into develop.

@MrPetovan Done. If this PR is too big for review I can split it to two parts: 1.) The introduction of the AppHelper interface and AppLegacy class and 2.) the replacement of App with AppHelper.

2024-11-17 14:03 UTC, MrPetovan requested changes

2024-11-17 14:03 UTC, MrPetovan commented on src/App/Page.php
> +	 * @param AppHelper                   $appHelper The Friendica App instance
Please update or remove the argument comment.

2024-11-17 14:03 UTC, MrPetovan commented on src/App/Page.php
> +	 * @param AppHelper                   $appHelper The Friendica App
Please update or remove the argument comment.

2024-11-17 14:03 UTC, MrPetovan commented on src/DI.php
> +	 * @deprecated 2024.12 use DI::apphelper() instead
Style preference, I feel like it reads better.
```suggestion
	 * @deprecated since 2024.12 use DI::apphelper() instead
```

2024-11-17 14:03 UTC, MrPetovan commented on src/Module/Profile/Index.php
> +	protected $appHelper;
Why the different scope for this property?

2024-11-17 14:03 UTC, MrPetovan commented on src/Module/Profile/Photos.php
> +	protected $appHelper;
Why the different scope for this property?

2024-11-17 14:03 UTC, MrPetovan commented on src/Module/Profile/Profile.php
> +	protected $appHelper;
Why the different scope for this property?

2024-11-17 14:03 UTC, MrPetovan commented on src/App.php
> +	public function __construct(
While you're at it, please move the constructor definition before all the other methods, below the property list.

2024-11-17 14:03 UTC, MrPetovan commented on src/DI.php
> +	public static function apphelper(): AppHelper
Please rename to snakeCase:
```suggestion
	public static function appHelper(): AppHelper
```

2024-11-17 17:35 UTC, Art4 commented on src/DI.php
> +	 * @deprecated 2024.12 use DI::apphelper() instead
I feel the same, but thats not how the phpdoc syntax works:

> Syntax
> 
> `@deprecated [<Semantic Version>] [<description>]`

https://docs.phpdoc.org/guide/references/phpdoc/tags/deprecated.html

2024-11-17 18:07 UTC, Art4 commented on src/Module/Profile/Index.php
> +	protected $appHelper;
my mistake, will correct this to `private`.

2024-11-17 19:53 UTC, Art4 commented on src/App/Page.php
> +	 * @param AppHelper                   $appHelper The Friendica App instance
removed

2024-11-17 19:54 UTC, Art4 commented on src/App/Page.php
> +	 * @param AppHelper                   $appHelper The Friendica App
removed.

2024-11-17 19:54 UTC, Art4 commented on src/Module/Profile/Index.php
> +	protected $appHelper;
fixed.

2024-11-17 19:54 UTC, Art4 commented on src/Module/Profile/Photos.php
> +	protected $appHelper;
fixed.

2024-11-17 19:54 UTC, Art4 commented on src/Module/Profile/Profile.php
> +	protected $appHelper;
fixed.

2024-11-17 19:54 UTC, Art4 commented on src/App.php
> +	public function __construct(
done.

2024-11-17 20:00 UTC, Art4 commented on src/DI.php
> +	public static function apphelper(): AppHelper
Done.

2024-11-17 20:02 UTC, Art4 commented
I will split the introduction of the AppHelper interface and AppLegacy class into a separate PR.

2024-11-18 15:37 UTC, MrPetovan approved these changes

2024-11-18 15:37 UTC, merged