Merge 2024.09-rc branch into develop
friendica/friendica pull request #14555
Opened 2024-11-15 14:47 UTC by Art4

The `2024.09-rc` branch is multiple commits away from the `develop` branch. This leads to PRs, where we has to wait for a release, before they could be merge, like #14529. This should be considered as tecnical dept. To quote the [refactoring.guru](https://refactoring.guru/refactoring/technical-debt) as source:

> **Long-term simultaneous development in several branches**
> 
> This can lead to the accumulation of technical debt, which is then increased when changes are merged. The more changes made in isolation, the greater the total technical debt.

Waiting for a release hinders the development. Even if we wait for the release every open PR has the potential for new git conflicts that has to be fixed in every PR. This should not be an issue.

This PR merges the `2024.09-rc` branch into the `develop` branch, so I can fix more potential errors reported by PHPStan level 0. I recommend to port every commit into a `rc` directly to the `develop` branch or at least once in a week.

2024-11-15 15:02 UTC, nupplaphil requested changes

2024-11-15 15:02 UTC, nupplaphil commented on VERSION
Plz beware of the version-code mixups. :)
f.e. docker has some upgrade-checks based on it.

2024-11-15 15:25 UTC, Art4 commented on VERSION
Thank you :+1: Yes, I'm aware that there are version mixups, but I'm not sure atm how they have to been solved. Should this be `2024.12-dev` now? (Another reason why there should no isolated development branches.)

2024-11-15 15:43 UTC, Art4 commented on src/App.php
> +	const VERSION  = '2024.09-rc';
?
```suggestion
	const VERSION  = '2024.12-dev';
```

2024-11-15 15:43 UTC, Art4 commented on VERSION
> +2024.09-rc
?
```suggestion
2024.12-dev
```

2024-11-15 15:43 UTC, Art4 commented on database.sql
> +-- Friendica 2024.09-rc (Yellow Archangel)
?
```suggestion
-- Friendica 2024.12-dev (Yellow Archangel)
```

2024-11-15 19:17 UTC, MrPetovan commented
The theory behind the RC branch is that during the RC period, only fixes should be committed to the RC branch, while new features/enhancements should be committed for the next release on the develop branch. After the release, the develop branch is brought up to speed with the RC fixes and development carries on.

In practice, since @annando is the only main developer on Friendica, the RC period can stretch longer than the expected 1 month, and features/enhancements end up making their way in the RC branch as well. However, I don't think changing this workflow for anything more involved would be warranted. We're already not complying very well with our simple structure, so we probably wouldn't gain more from adding more complexity to the structure.

> Please see also the [famous git flow by Vincent Driessen](https://nvie.com/posts/a-successful-git-branching-model/), where commits to a RC branch should be continuous merge back into the develop branch.

I found the RC branch workflow of this flow very similar to ours, with a merge back to develop at the end of the release period, with no "continuous" merge back that I could see.

2024-11-16 08:49 UTC, Art4 commented
> The theory behind the RC branch is that during the RC period, only fixes should be committed to the RC branch, while new features/enhancements should be committed for the next release on the develop branch. After the release, the develop branch is brought up to speed with the RC fixes and development carries on.
> 
> In practice, since @annando is the only main developer on Friendica, the RC period can stretch longer than the expected 1 month, and features/enhancements end up making their way in the RC branch as well. However, I don't think changing this workflow for anything more involved would be warranted. We're already not complying very well with our simple structure, so we probably wouldn't gain more from adding more complexity to the structure.

@MrPetovan All of this is fine. I see no need to change the workflow for RC branches. By the way is this the nearly exact same workflow as in git flow described.

> > Please see also the [famous git flow by Vincent Driessen](https://nvie.com/posts/a-successful-git-branching-model/), where commits to a RC branch should be continuous merge back into the develop branch.
> 
> I found the RC branch workflow of this flow very similar to ours, with a merge back to develop at the end of the release period, with no "continuous" merge back that I could see.

Yes, and the missing continuous merges back to develop is the only thing I recommend to change. :blush: I am willing to take on this task. I only need some advise If the version naming is correct 

I bumped the version to `2024.12-dev` as seen in https://github.com/friendica/friendica/commit/60ffd8fe7882ad0ec315accd6102df30a07a4cc2 and I merged the newest changes from the `develop` branch and fixed the conflicts.

2024-11-16 17:32 UTC, nupplaphil approved these changes

2024-11-16 18:00 UTC, MrPetovan approved these changes

2024-11-16 18:00 UTC, merged