Update FAQ.md
friendica/friendica pull request #7181
Opened 2019-05-24 17:31 UTC by AndyHee

Update documention about deletion process.

This closes #870

2019-05-24 17:36 UTC, MrPetovan requested changes

2019-05-24 17:36 UTC, MrPetovan commented on doc/FAQ.md
> +If you delete your account, it will be scheduled for permanent deletion in *seven days*. As soon as you activate the deletion process you won't be able to logon any more. Only the administrator of yo
`login`

2019-05-24 17:36 UTC, MrPetovan commented on doc/FAQ.md
> +After the elapsed time of seven days, all your posts, messages, photos, and personal information stored on your node will be deleted. Your node will also issue removal requests to all your contacts;
Formatting: Please add a line feed after periods.

2019-05-24 17:36 UTC, MrPetovan commented on doc/FAQ.md
> +If you delete your account, it will be scheduled for permanent deletion in *seven days*. As soon as you activate the deletion process you won't be able to logon any more. Only the administrator of yo
Formatting: Please add a line feed after periods.

2019-05-24 18:12 UTC, AndyHee commented
Had forgotten about the line breaks. All done now.

2019-05-24 18:30 UTC, MrPetovan approved these changes

2019-05-24 18:31 UTC, merged

2019-06-25 05:13 UTC, tobiasd commented on doc/FAQ.md
> +Only the administrator of your node can halt this process prior to permanent deletion.
How? Is it documented anywhere for the admin how to stop the deletion?