2020.09 changelog
friendica/friendica pull request #9146
Opened 2020-09-06 12:38 UTC by tobiasd

2020-09-07 16:38 UTC, MrPetovan requested changes

2020-09-07 16:38 UTC, MrPetovan commented on CHANGELOG
> +    Enhanced sample lighttpd and nginx configs [MrTetovan, tobiasd]
😂
```suggestion
    Enhanced sample lighttpd and nginx configs [MrPetovan, tobiasd]
```

2020-09-07 17:12 UTC, annando commented on CHANGELOG
> +    Enhanced sample lighttpd and nginx configs [MrTetovan, tobiasd]
Monsieur la tête aux vin. :grin:

2020-09-07 17:17 UTC, tobiasd commented on CHANGELOG
> +    Enhanced sample lighttpd and nginx configs [MrTetovan, tobiasd]
One typo removed, one ypot added...

2020-09-09 05:51 UTC, annando commented on CHANGELOG
> +    Fixed a problem that leakted sensitive information [Roger Meyer, MrPetovan]
"Leaked"

2020-09-15 11:51 UTC, MrPetovan approved these changes

2020-09-17 16:59 UTC, annando commented on CHANGELOG
> +    Fixed a problem while displaying previews for empty feets [annando]
"Fixed a problem for empty preview data when importing feed posts"

2020-09-20 15:14 UTC, MrPetovan approved these changes

2020-09-20 19:04 UTC, merged