Create new namespace "Domain" for Domain Driven Design classes
friendica/friendica pull request #9190
Opened 2020-09-12 20:50 UTC by nupplaphil

At the hackathon, I'd like to discuss more about "DDD" and the reason behind it.

Therefore I'd like to cleanup a little bit the structure before.
Everything "DDD" relevant is now moved under the new `Domain` namespace.

As you now can see, not every factory, model or object is moved there, which should indicate the difference between "classic" factory, model, objects classes and the DDD relevant ones.

We now can see/discuss better the patterns behind it.

Draft PR until @MrPetovan say it's OK for him :-)

2020-09-12 23:04 UTC, MrPetovan requested changes

2020-09-12 23:04 UTC, MrPetovan commented on src/Module/Register.php
> +								  'type'         => \Friendica\Domain\Model\Notify\Type::SYSTEM,
Whoa, the indentation here is out of whack.

2020-09-12 23:04 UTC, MrPetovan commented
So, what are the non-static classes that didn't make the cut?

2020-09-13 05:26 UTC, annando commented
@nupplaphil be prepared for long hours explanations at the hackathon, preferably in German when @MrPetovan is not around, since I don't understand the linked text from the beginning. I never heard of "Bounded Contexts", "Microservice", "CQRS", "Command handlers", "Event Sourcing", ... And what is a "Domain" in this context at all?

2020-09-13 08:32 UTC, annando commented
Being a little bit more awake, I have some questions to the text and your implementation. I don't think that adding `/Domain` isn't in the intention of that text. The text describes the "Domain" as some kind of department/purpose separator and "Domain" should only be used when there are several. So - I think - we had to define with "Domains" we do have. And if I understood the text then the domain path should contain the domain description in it, like the example `/Domain/Legal/Company/France/RegistrationNumber/Siret.php`.

Having this in mind, I don't think that `\Friendica\Domain\Repository\Notify` and `Friendica\Domain\Model\Notify\Type` are the right names, because - I think - "Repository" and "Model" are no domains, but "Notify" possibly is?

Concerning the separation, I think that we can separate between backend, API, CLI and frontend. And the backend - since it is really large - should be separated in the protocols, the message processing, communication, ...

2020-09-13 08:39 UTC, nupplaphil commented
I've to think more about it, but as far as I understood you @annando I fully agree and that's what I want to discuss with you. The domain namespace is therefore temporary to exactly discuss this type of re-organisatin away from namespace per class types to namespaces per domain :-)

2020-10-01 21:05 UTC, nupplaphil commented
Closing because it isn't a good idea..

2020-10-01 21:05 UTC, closed without merging

2020-10-01 21:17 UTC, annando commented
Have you abandon it completely or do you just need to refine it? I really would like to see some class approach that I am able to understand, I must confess :-) So some (online) meeting in the next time between (at least) you, @MrPetovan and me would sound cool to me.

2020-10-01 21:26 UTC, nupplaphil commented
I'd like to take a step forward to "real" domains as discussed in the dev forum. This would mean not a separation by types (repo, model, ...) and instead a separation by functionality/domain (api/front-end/protocol and a layer under it the type differention). And each domain has low bounds inside but strict bounds outside to other domains

2020-10-03 15:00 UTC, MrPetovan commented
What about the "common" classes that can be used by multiple endpoints like models?