Introduce possibility for mapping $_SERVER variables to config-cache values
friendica/friendica pull request #9373
Opened 2020-10-06 18:17 UTC by nupplaphil

This PR introduces the possibility to have three different source of config entries:
- A config file
- A db entry
- A $_SERVER env variable

Due the problem that db values may override env variables again (like when using `$config->load()`), I prioritize the sources
Low prio - config file
Middle prio - db entry
High prio - $_SERVER var

So in the end, even the config tries to load db variables again, the $_SERVER variable based config entries remain.

There's a new mapping table to map $_SERVER env variables onto the config:
`static/env.config.php`

After this PR, I think I do want to add some of the docker specific env variables into this config and add a "doc" in this repo for it. So other deployment types (or other container/virtualization possibilities) can reuse the $_SERVER config variables.

2020-10-06 18:42 UTC, MrPetovan reviewed
That's it?

2020-10-06 18:54 UTC, MrPetovan requested changes

2020-10-06 18:54 UTC, MrPetovan commented on src/Database/Database.php
> +			$port = trim(trim($this->configCache->get('database', 'port')));
```suggestion
			$port = trim($this->configCache->get('database', 'port'));
```

2020-10-06 18:54 UTC, MrPetovan commented on static/dependencies.config.php
> +			[Dice::INSTANCE => '$basepath']
Please keep the trailing comma, it improves the diff readability when adding an item at the end of arrays.

2020-10-06 18:54 UTC, MrPetovan commented on static/env.config.php
> + * Main mapping table of environment variables to correct config values
```suggestion
 * Main mapping table of environment variables to namespaced config values
```

2020-10-06 19:04 UTC, MrPetovan approved these changes

2020-10-06 19:19 UTC, AlfredSK commented
What if I have a setting already stored in the DB (prio med) and then set it via config file (prio low)?

2020-10-06 19:21 UTC, MrPetovan commented
It's going to be ignored like it already used to be. Ideally, this should never happen as your config file should only override config keys present in `static/defaults.config.php` which aren't set in the DB.

2020-10-06 19:24 UTC, AlfredSK commented
> It's going to be ignored _like it already used to be_.

Ah! Ok. I wasn't aware of that. Thanks.

2020-10-08 18:24 UTC, nupplaphil commented
Ping @MrPetovan :D

2020-10-08 19:00 UTC, merged

2020-10-08 19:00 UTC, MrPetovan commented
I should be notified when tests end.

2020-10-08 21:49 UTC, AlfredSK commented
I get an info bubble with "invalid storage backend settings" now when I save the settings in admin panel.

2020-10-08 21:55 UTC, MrPetovan commented
Did you ever migrate from the legacy backend?

2020-10-08 22:01 UTC, AlfredSK commented
Well, there was a time where we only had one backend - the database. :-) And yes, I migrated from 'database' to 'filesystem' right after the filesystem backend had been intoduced.

2020-10-08 23:31 UTC, MrPetovan commented
Hmmm, I thought it was because I’ve never selected a storage backend, so the value would be invalid when I submit the site settings.

2020-10-09 15:11 UTC, nupplaphil commented
I'll take a look

2020-10-09 18:22 UTC, AlfredSK commented
Btw. I do not get PHP errors. I only see three lines logged into Friendica's log when I set log level to INFO. Should I post them here? They don't look concerning.