Adding an on-demand scrollbar for mobile off-canvas menu
friendica/friendica pull request #9388
Opened 2020-10-07 20:04 UTC by vinzv

This should fix #9383

2020-10-07 21:40 UTC, MrPetovan requested changes
Have you verified your fix to work?

2020-10-07 21:40 UTC, MrPetovan commented on view/theme/frio/css/style.css
> +	overflow: auto;
Please use the same indentation as the rest of the selector at least.

2020-10-07 21:41 UTC, MrPetovan commented
Funnily enough the length of your branch name is breaking GitHub’s mobile view:
![BB4530F6-C4D6-4E28-9271-62182E9EDBA1](https://user-images.githubusercontent.com/925415/95391024-4b9b1900-08c4-11eb-83fb-767b6ba6fb1b.png)

2020-10-08 12:54 UTC, vinzv commented
> Have you verified your fix to work?

Yes, this is how it looks at /admin for example:

![grafik](https://user-images.githubusercontent.com/74432/95461154-2bc42d80-0976-11eb-80da-81f8ade1fabe.png)

2020-10-08 14:58 UTC, MrPetovan requested changes

2020-10-08 14:58 UTC, MrPetovan commented on view/theme/frio/templates/jot.tpl
> +                                                <li role="presentation"><button type="button" class="btn-link" id="profile-emoji" onclick="myFunction();" title="{{$setloc}}"><i class="fa fa-smile-o"
I believe this is work in progress code that shouldn't be part of this PR.

2020-10-08 15:01 UTC, MrPetovan commented
> Yes, this is how it looks at /admin for example:

Is the low contrast expected?

2020-10-08 15:02 UTC, MrPetovan approved these changes

2020-10-08 15:02 UTC, merged

2020-10-08 15:34 UTC, vinzv commented
Expected? Yes. It was like that before.
Wanted? No. But that's out of scope here.