Don't change resharer when resharing/add mobile button
friendica/friendica pull request #9412
Opened 2020-10-11 17:41 UTC by annando

This fixes the problem that resharing a reshared post changed the resharer. And also the "announce" button is added in Frio for mobile users.

2020-10-11 17:44 UTC, MrPetovan approved these changes

2020-10-11 19:51 UTC, annando commented
@MrPetovan do you want to merge it or should I add some stuff? I already had done some more work, like announcing of Diaspora posts and renaming the functions in "Share" and "Quoted Share".

2020-10-11 19:52 UTC, MrPetovan commented
You can add more stuff.

2020-10-11 20:11 UTC, annando commented
@MrPetovan added

2020-10-11 22:14 UTC, MrPetovan requested changes

2020-10-11 22:14 UTC, MrPetovan commented on src/Object/Post.php
> +				$buttons['share'] = [DI::l10n()->t('Quote and share this'), DI::l10n()->t('Quoted Share')];
A "quoted share" has a specific meaning in English finance,
```suggestion
				$buttons['share'] = [DI::l10n()->t('Quote and share this'), DI::l10n()->t('Quote Share')];
```

2020-10-12 02:38 UTC, MrPetovan requested changes
I believe you need to update the messages.po after the last translation string change.

2020-10-12 03:49 UTC, MrPetovan approved these changes

2020-10-12 03:49 UTC, merged