API: accounts and trends
friendica/friendica pull request #9481
Opened 2020-10-31 22:36 UTC by annando

Three new Mastodon endpoints are now added.

2020-10-31 23:06 UTC, MrPetovan approved these changes

2020-10-31 23:08 UTC, MrPetovan requested changes
Please update the API documentation regarding the implemented Mastodon endpoints. File is `doc/API-Mastodon.md`.

2020-10-31 23:52 UTC, annando commented
@MrPetovan done.

2020-11-01 00:05 UTC, MrPetovan approved these changes

2020-11-01 00:05 UTC, merged

2020-11-01 06:48 UTC, tobiasd commented
Could you please apply the documentation in the wiki... ;)