Remove unused contacts
friendica/friendica pull request #9623
Opened 2020-12-05 21:27 UTC by annando

This helps with the problem of the huge storage space needed for the photos. The main contributor for this are the cached avatar pictures. So now we remove all public contacts (and their avatars) when first: either they are archived and hadn't been reachable for at least a year or are contacts from any non federated networks. And second: There are no items (and other stuff) belonging to this contact.

This reduced the number of contacts on my system from 900,000 to 600,000.

Some future PR could remove the cached pictures of unused - but unarchived - fediverse contacts.

2020-12-05 21:36 UTC, MrPetovan requested changes

2020-12-05 21:36 UTC, MrPetovan commented on src/Worker/RemoveUnusedContacts.php
> +class RemoveUnusedContacts {
Code standards: please add a new line before class opening brace.

2020-12-05 21:36 UTC, MrPetovan commented on src/Worker/RemoveUnusedContacts.php
> +	public static function execute() {
Code standards: please add a new line before method opening brace.

2020-12-05 21:58 UTC, annando commented on src/Worker/RemoveUnusedContacts.php
> +class RemoveUnusedContacts {
Done

2020-12-05 21:58 UTC, annando commented on src/Worker/RemoveUnusedContacts.php
> +	public static function execute() {
Done

2020-12-06 00:32 UTC, MrPetovan approved these changes

2020-12-06 00:33 UTC, merged