Redo right offcanvas menu
friendica/friendica pull request #9844
Opened 2021-01-21 22:21 UTC by Extarys

This is a test. It only replaces the right menu on mobile for now. If everything is okay I'll later do the same to the left offcanvas menu.

I also changed the color of the search icon in mobile view.

This is a start for #9837 

Result:
![image](https://user-images.githubusercontent.com/11581433/105419478-c89c9500-5c0c-11eb-9016-9a41d246265d.png)

2021-01-21 22:23 UTC, Extarys commented on view/theme/frio/js/theme.js
> +	// Right offcanvas elements
Code change starts here

2021-01-22 02:36 UTC, MrPetovan commented
So, we had issues with fixing the formatting of files that are changed in a PR before, and the solution if you can't prevent your IDE from reformatting the files you're touching is to commit the reformatted files *without your changes* first, and then submitting your changes in additional commits. This allows a commit-by-commit review of the PR without having to guess where the real changes are and where the formatting changes are.

2021-01-22 02:36 UTC, MrPetovan requested changes
So, we had issues with fixing the formatting of files that are changed in a PR before, and the solution if you can't prevent your IDE from reformatting the files you're touching is to commit the reformatted files without your changes first, and then submitting your changes in additional commits. This allows a commit-by-commit review of the PR without having to guess where the real changes are and where the formatting changes are.

2021-01-22 13:44 UTC, Extarys commented
Wise.

Can you tell me how I can "replay" these changes on top of the current develop version (HEAD?) once #9850 is merged?

2021-01-22 13:57 UTC, MrPetovan commented
Ha, you won't like it, because it will involve `git rebase` and probably fixing conflicts since I've been asking you some changes over at #9850.

Depending on the extensiveness of the changes in `nav.tpl`, you may be better off discarding all the changes in the file and starting over once this branch is rebased on top of the updated `develop` after the formatting PR is merged.

Basically, it would go like this once the PR is merged:
```
# update your friendica remote with the updated develop branch
> git fetch --all
# update your local develop branch to the friendica state and push it to your fork
> git checkout develop && git rebase friendica/develop && git push
# Switch to your working branch for this current PR
> git checkout offcanvas
# Replay your branch on top of the updated develop
> git rebase develop
# CONFLICTS! Good luck.
# Once you're done, you need to force-push your branch since you're rewriting history.
# It's fine in this case because it's your branch on your fork. It's more problematic with a shared repo.
> git push --force
```

2021-01-22 16:56 UTC, Extarys commented
@MrPetovan , the Git Master.

There are some ashes here and there of the old offcanvas that I'll clean up when I change the left offcanvas. Either today or tomorrow, I'll wait a little once this is pushed in case mobile users notice breaking bugs. (Shouldn't happen, but better safe than sorry)

2021-01-22 16:57 UTC, MrPetovan requested changes

2021-01-22 16:57 UTC, MrPetovan commented on view/theme/frio/templates/nav.tpl
> +					<button type="button" class="navbar-toggle offcanvas-right-toggle pull-right" aria-controls="myNavmenu"
The `aria-controls` attribute must be updated.
```suggestion
					<button type="button" class="navbar-toggle offcanvas-right-toggle pull-right" aria-controls="offcanvasUsermenu"
```

2021-01-22 17:01 UTC, MrPetovan approved these changes

2021-01-22 17:02 UTC, merged